"""Phase 3-c: verify getdatm.py -- both the DAt.q computation and the
dense-Lorentz-block DAt.denq correction (via _native.adendotd) -- against
the real Octave build.

Oracle data (tests/fixtures/sdinit/getdatm.mat,
tests/fixtures/sdinit/getdatm_dense.mat) is generated by
tools/generate_getdatm_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.getdatm import getDAtm  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _to_dense(x):
    return np.asarray(x.todense() if sp.issparse(x) else x)


def test_getdatm_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "getdatm.mat")
    At2 = sp.csc_matrix(data["At2"])
    K2 = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    densemat = data["dense"][0, 0]
    dense = {
        "l": 0,
        "q": densemat["q"].ravel().astype(np.int64),
        "cols": densemat["cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix((At2.shape[1], 0)),
    }
    DAtdenq = sp.csc_matrix((At2.shape[1], 0))

    DAt = getDAtm(At2, None, dense, DAtdenq, d, K2)

    DAt_exp = data["DAt"][0, 0]
    q_exp = _to_dense(DAt_exp["q"])
    np.testing.assert_allclose(_to_dense(DAt["q"]), q_exp, rtol=1e-9, atol=1e-11)


def test_getdatm_dense_lorentz_block_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "getdatm_dense.mat")
    At2 = sp.csc_matrix(data["At2"])
    K2 = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    densemat = data["dense2"][0, 0]
    dense = {
        "l": int(densemat["l"].item()),
        "q": densemat["q"].ravel().astype(np.int64),
        "cols": densemat["cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix(densemat["A"]),
    }
    DAtdenq = sp.csc_matrix(data["DAtdenq2"])

    DAt = getDAtm(At2, None, dense, DAtdenq, d, K2)

    DAt2_exp = data["DAt2"][0, 0]
    q_exp = _to_dense(DAt2_exp["q"])
    denq_exp = _to_dense(DAt2_exp["denq"])

    np.testing.assert_allclose(_to_dense(DAt["q"]), q_exp, rtol=1e-9, atol=1e-11)
    np.testing.assert_allclose(_to_dense(DAt["denq"]), denq_exp, rtol=1e-9, atol=1e-11)
    # getDAtm.m zeroes DAt.q's dense-block rows after folding their
    # contribution into DAt.denq.
    np.testing.assert_array_equal(_to_dense(DAt["q"][dense["q"] - 1, :]), 0.0)
