"""Phase 2 cluster 2: verify dpr1fact/fwdpr1/bwdpr1 (the "dense column"
product-form rank-1 factorization used in SeDuMi's PCG preconditioner)
against the real Octave/MEX build.

This is the most intricate remaining cluster: dpr1fact.c's "Lsym.dz"
input is not a plain sparse matrix in the usual sense -- it is a
"cumulative compact row set" scheme (each column's stored nonzeros are
only the rows *newly introduced* relative to previous columns, not a
per-column-independent pattern; dz.jc[n] <= m always). Hand-constructing
a valid multi-column example required reverse-engineering this from
dpr1fact.c/fwdpr1.c directly (see
tools/generate_dpr1fact_oracle.m) rather than from any doc
comment -- the header comments describe the *mathematical* contract
(diag(d)+x*diag(smult)*x' = product-of-L * diag(d_out) * product-of-L')
but not this storage detail.

Fixtures (generated by tools/generate_dpr1fact_oracle.m, and
committed so this test does not require Octave to run) cover n=1
(single dense column) and n=2 (two, with column 2's compact rows nested
beyond column 1's -- exercises fwprodform's/bwprodform's multi-block
loop, still without triggering pivoting). The pivoting branch (dopiv=1)
is not covered here.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cluster2"
CASES = ["dpr1fact_n1", "dpr1fact_n2"]
pytestmark = pytest.mark.skipif(
    not all((FIXTURE_DIR / f"{c}.mat").exists() for c in CASES),
    reason="dpr1fact fixtures not generated",
)


def _lden_dict(struct):
    return {
        "betajc": struct["betajc"].ravel(),
        "beta": struct["beta"].ravel(),
        "p": struct["p"].ravel(),
        "pivperm": struct["pivperm"].ravel(),
        "dopiv": struct["dopiv"].ravel(),
        "dz": struct["dz"].tocsc(),
        "perm": struct["perm"].ravel(),
        "first": struct["first"].ravel(),
    }


@pytest.mark.parametrize("case", CASES)
def test_dpr1fact_matches_octave_mex(case):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{case}.mat")
    Lden_oracle = data["Lden"][0, 0]

    Lsym = {
        "dz": data["dz"].tocsc(),
        "perm": data["perm"].ravel(),
        "first": Lden_oracle["first"].ravel(),
    }
    Lden, d_out = _native.dpr1fact(
        data["LAD"].tocsc(), data["d"].ravel(), Lsym,
        data["smult"].ravel(), float(data["maxu"].item()),
    )

    np.testing.assert_array_equal(Lden["betajc"], Lden_oracle["betajc"].ravel())
    np.testing.assert_allclose(Lden["beta"], Lden_oracle["beta"].ravel(), rtol=1e-10)
    np.testing.assert_allclose(Lden["p"], Lden_oracle["p"].ravel(), rtol=1e-10)
    np.testing.assert_array_equal(Lden["dopiv"], Lden_oracle["dopiv"].ravel())
    np.testing.assert_allclose(d_out, data["Ld"].ravel(), rtol=1e-10)


@pytest.mark.parametrize("case", CASES)
def test_fwdpr1_bwdpr1_match_octave_mex(case):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{case}.mat")
    Lden = _lden_dict(data["Lden"][0, 0])
    b = data["b"].ravel()

    y = _native.fwdpr1(Lden, b)
    z = _native.bwdpr1(Lden, b)

    np.testing.assert_allclose(y, data["y"].ravel(), rtol=1e-10)
    np.testing.assert_allclose(z, data["z"].ravel(), rtol=1e-10)


@pytest.mark.parametrize("case", CASES)
def test_dpr1fact_pipeline_solves_documented_equation(case):
    """Independent of the oracle: deninfac.m's own recipe --
    bwdpr1(Lden, fwdpr1(Lden,b) ./ d_out) -- must solve
    (diag(d) + LAD*diag(smult)*LAD') @ z = b, per dpr1fact.c's own
    documented contract."""
    data = scipy.io.loadmat(FIXTURE_DIR / f"{case}.mat")
    LAD = data["LAD"].tocsc()
    d = data["d"].ravel()
    smult = data["smult"].ravel()
    maxu = float(data["maxu"].item())
    Lsym = {
        "dz": data["dz"].tocsc(),
        "perm": data["perm"].ravel(),
        "first": data["Lden"][0, 0]["first"].ravel(),
    }

    Lden, d_out = _native.dpr1fact(LAD, d, Lsym, smult, maxu)
    Lden["dz"] = Lsym["dz"]
    Lden["perm"] = Lsym["perm"]
    Lden["first"] = Lsym["first"]

    rng = np.random.default_rng(hash(case) % (2**32))
    b = rng.standard_normal(LAD.shape[0])

    w = _native.fwdpr1(Lden, b) / d_out
    z = _native.bwdpr1(Lden, w)

    M = np.diag(d) + LAD.toarray() @ np.diag(smult) @ LAD.toarray().T
    np.testing.assert_allclose(M @ z, b, atol=1e-8)
