"""Phase 3-c: verify maxstep.py against the real Octave build, using
auxx built the same way wregion.m does (uxc.tdet from vfrm.lab,
uxc.u = psdfactor(x,K)) on the same mixed L+Lorentz+real-SDP problem as
the recent updtransfo fixture.

Oracle data (tests/fixtures/sdinit/maxstep.mat) is generated by
tools/generate_maxstep_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.maxstep import maxstep  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_maxstep_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "maxstep.mat")
    K = _load_K(data["K2"][0, 0])
    x = data["x"].ravel()
    dx = data["dx"].ravel()
    auxxmat = data["auxx"][0, 0]
    auxx = {"u": auxxmat["u"].ravel(), "tdet": auxxmat["tdet"].ravel()}

    tp = maxstep(dx, x, auxx, K)
    assert tp == pytest.approx(float(data["tp"].item()), rel=1e-6)
