"""Verify incorder.incorder against the real Octave/MEX build (incorder.c
-- see incorder.py's module docstring for why this is a from-scratch
port rather than a ctypes binding).

Oracle data (tests/fixtures/incorder/*.mat) is generated by
tools/generate_incorder_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.incorder import incorder  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "incorder"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="incorder fixtures not generated"
)


def _to_csc(mat_entry):
    return sp.csc_matrix(mat_entry)


def test_incorder_default_args():
    data = scipy.io.loadmat(FIXTURE_DIR / "case1.mat")
    At1 = _to_csc(data["At1"])
    perm1 = data["perm1"].ravel().astype(np.int64)
    dz1 = _to_csc(data["dz1"])

    perm, dz = incorder(At1)

    np.testing.assert_array_equal(perm, perm1)
    np.testing.assert_allclose(dz.toarray(), dz1.toarray())


def test_incorder_with_ajc1_and_ifirst():
    data = scipy.io.loadmat(FIXTURE_DIR / "case2.mat")
    At2 = _to_csc(data["At2"])
    Ablkjc2 = data["Ablkjc2"].astype(np.int64)
    ifirst2 = int(data["ifirst2"].item())
    perm2 = data["perm2"].ravel().astype(np.int64)
    dz2 = _to_csc(data["dz2"])

    perm, dz = incorder(At2, Ablkjc2[:, 1], ifirst2)

    np.testing.assert_array_equal(perm, perm2)
    np.testing.assert_allclose(dz.toarray(), dz2.toarray())


def test_incorder_tied_counts():
    data = scipy.io.loadmat(FIXTURE_DIR / "case3.mat")
    At3 = _to_csc(data["At3"])
    perm3 = data["perm3"].ravel().astype(np.int64)
    dz3 = _to_csc(data["dz3"])

    perm, dz = incorder(At3)

    np.testing.assert_array_equal(perm, perm3)
    np.testing.assert_allclose(dz.toarray(), dz3.toarray())


def test_incorder_degenerate_column():
    data = scipy.io.loadmat(FIXTURE_DIR / "case4.mat")
    At4 = _to_csc(data["At4"])
    perm4 = data["perm4"].ravel().astype(np.int64)
    dz4 = _to_csc(data["dz4"])

    perm, dz = incorder(At4)

    np.testing.assert_array_equal(perm, perm4)
    np.testing.assert_allclose(dz.toarray(), dz4.toarray())
