"""Phase 3 (symbolic Cholesky ordering, step 2): verify the
symbolic_cholesky() ctypes binding (sfinit_/symfct_/expandsub, the
highest-complexity kernel in the whole codebase -- Ng/Peyton's algorithm,
translated from Fortran) produces EXACTLY the same L.L sparsity pattern,
L.perm and L.xsuper as the real Octave/MEX symfctmex(), for the exact
same (X, perm) input symbchol.m itself would pass (perm coming from the
real ordmmdmex()).

The oracle files (tests/fixtures/ordmmd/*_symfct_oracle.mat) are
generated by tools/generate_symfct_oracle.m and committed, so
this test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "ordmmd"


def _fixture_names():
    if not FIXTURE_DIR.exists():
        return []
    return sorted(
        p.stem
        for p in FIXTURE_DIR.glob("*.mat")
        if not p.stem.endswith(("_oracle", "_symfct_oracle"))
    )


@pytest.mark.skipif(not _fixture_names(), reason="symfct fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_symbolic_cholesky_matches_octave_mex_exactly(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    oracle = scipy.io.loadmat(FIXTURE_DIR / f"{name}_symfct_oracle.mat")

    A = data["A"].tocsc()
    ordmmd_perm_1indexed = np.asarray(oracle["ordmmd_perm"]).squeeze().astype(np.intp)
    ordmmd_perm_0indexed = ordmmd_perm_1indexed - 1

    # Sanity-check this test's own input matches the independently-tested
    # ordmmd() binding, so a mismatch below is unambiguously symfct_'s,
    # not a stale/inconsistent fixture.
    np.testing.assert_array_equal(_native.ordmmd(A) + 1, ordmmd_perm_1indexed)

    result = _native.symbolic_cholesky(A, ordmmd_perm_0indexed)

    expected_perm = np.asarray(oracle["perm"]).squeeze().astype(np.intp) - 1
    expected_xsuper = np.asarray(oracle["xsuper"]).squeeze().astype(np.intp) - 1
    expected_L = oracle["Lpattern"].tocsc()

    np.testing.assert_array_equal(result["perm"], expected_perm)
    np.testing.assert_array_equal(result["xsuper"], expected_xsuper)

    got_L = result["L"]
    assert got_L.shape == expected_L.shape
    np.testing.assert_array_equal(got_L.indptr, expected_L.indptr)
    np.testing.assert_array_equal(got_L.indices, expected_L.indices)


@pytest.mark.skipif(not _fixture_names(), reason="symfct fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_symbolic_cholesky_pattern_is_lower_triangular_and_covers_diagonal(name):
    """Independent of the Octave oracle: L must be a valid Cholesky
    sparsity pattern -- lower triangular with a full diagonal."""
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    A = data["A"].tocsc()
    perm = _native.ordmmd(A)

    result = _native.symbolic_cholesky(A, perm)
    L = result["L"].tocoo()

    assert np.all(L.row >= L.col), "L must be lower triangular"
    diag_present = set(zip(L.row[L.row == L.col], L.col[L.row == L.col]))
    assert len(diag_present) == A.shape[0], "every diagonal entry must be present"
