"""Phase 3-c: verify pcg.py (sparfwslv, sparbwslv, loopPcg, wrapPcg)
against the real Octave build, using a genuine A*P(d)*A' system built
from the same mixed L+Lorentz+real-SDP problem/scaling point `d` as the
recent sdinit/getDAtm/PopK fixtures.

Oracle data (tests/fixtures/sdinit/pcg.mat) is generated by
tools/generate_pcg_oracle.m and committed, so this test does
not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.pcg import loopPcg, wrapPcg  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "pcg.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    DAtmat = data["DAt"][0, 0]
    q = DAtmat["q"]
    DAt = {"q": np.asarray(q.todense() if sp.issparse(q) else q)}
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "q": densemat["q"].ravel()}
    Lmat = data["Lstruct"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
    }
    Lden = {"betajc": np.array([1])}
    At2 = sp.csc_matrix(data["At2"])
    cg = {
        "qprec": 1,
        "restol": 5e-3,
        "stagtol": 5e-14,
        "maxiter": 49,
        "refine": 1,
    }
    return data, K, d, DAt, dense, L, Lden, At2, cg


def test_wrappcg_matches_octave():
    # L.L/L.d (from blkchol) factor ADA(perm,perm), not ADA itself
    # (`ADA(L.perm,L.perm) = L.L*diag(L.d)*L.L'`, per sedumi.m's own
    # comment) -- wrapPcg.m/loopPcg.m never reference L.perm themselves,
    # so real SeDuMi applies this permutation ONCE, up front, to the
    # whole m-dimensional constraint space (At's columns, b, y) for the
    # entire algorithm, never un-permuting until the very end. Since this
    # test drives wrapPcg/loopPcg directly (not through a full sedumi.m
    # setup), it reproduces that by permuting At2's columns and rb going
    # in, and un-permuting y coming out -- exactly the same convention
    # test_sparse_solve_pipeline.py already uses for fwsolve/bwsolve.
    data, K, d, DAt, dense, L, Lden, At2, cg = _load()
    perm = data["Lstruct"][0, 0]["perm"].ravel().astype(np.int64) - 1

    rb = data["rb"].ravel()
    rv = data["rv"].ravel()
    y0 = float(data["y0"].item())
    maxRb = float(data["R"][0, 0]["maxRb"].item())

    # At2's columns (the constraint/m-space) and rb must be permuted the
    # same way ADA was before being factored, since L.L/L.d are the
    # Cholesky factors of ADA(perm,perm) -- see the module-level note.
    At2_perm = At2[:, perm]
    rb_perm = rb[perm]

    y, dx, k, r = wrapPcg(L, Lden, At2_perm, dense, d, DAt, K, rb_perm, rv, cg, min(1, y0) * maxRb)

    y_exp = data["wy"].ravel()
    y_unperm = np.empty_like(y)
    y_unperm[perm] = y
    np.testing.assert_allclose(y_unperm, y_exp, rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(dx, data["wdx"].ravel(), rtol=1e-6, atol=1e-8)
    assert k == int(data["wk"].item())


def test_looppcg_matches_octave():
    data, K, d, DAt, dense, L, Lden, At2, cg = _load()
    perm = data["Lstruct"][0, 0]["perm"].ravel().astype(np.int64) - 1

    bvec = data["bvec"].ravel()
    restol = float(data["restol"].item())
    At2_perm = At2[:, perm]
    bvec_perm = bvec[perm]

    y, k, DAy = loopPcg(L, Lden, At2_perm, dense, d, DAt, K, bvec_perm, None, 0.0, cg, restol)

    y_exp = data["ly"].ravel()
    y_unperm = np.empty_like(y)
    y_unperm[perm] = y
    np.testing.assert_allclose(y_unperm, y_exp, rtol=1e-6, atol=1e-8)
    assert k == int(data["lk"].item())
    np.testing.assert_allclose(DAy, data["lDAy"].ravel(), rtol=1e-6, atol=1e-8)
