"""Phase 3-d: golden-reference, end-to-end verification of sedumi.py
(the top-level driver) against the real Octave sedumi.m, on small LP,
SOCP (Lorentz), and PSD (K.s) problems -- covering primal-dual optimal
solutions as well as the dual-infeasible-with-improving-direction
outcome.

Oracle data (tests/fixtures/sedumi/*.mat) is generated by
tools/generate_sedumi_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.sedumi import sedumi  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sedumi"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sedumi fixtures not generated"
)


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld in ("f", "l"):
            K[fld] = int(val.item())
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


@pytest.mark.parametrize(
    "name",
    [
        "lp_feasible",
        "lp_free_feasible",
        "socp_feasible",
        "socp_two_blocks",
        "lp_infeasible",
        "rotated_cone_feasible",
        "lp_sparse_feasible",
        "sdp_feasible",
        "sdp_mixed_cones_feasible",
    ],
)
def test_sedumi_matches_octave(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    At = sp.csc_matrix(data["At"])
    b = _densify(data["b"])
    c = _densify(data["c"])
    K = _load_K(data["K"][0, 0])
    info_oct = data["info"][0, 0]

    x, y, info = sedumi(At, b, c, K)

    assert info["iter"] == int(info_oct["iter"].item())
    assert info["numerr"] == int(info_oct["numerr"].item())
    assert info["pinf"] == int(info_oct["pinf"].item())
    assert info["dinf"] == int(info_oct["dinf"].item())

    np.testing.assert_allclose(x, _densify(data["x"]), rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(y, _densify(data["y"]), rtol=1e-5, atol=1e-6)
