"""Verify _native.getada1/getada2/getada3 against the real Octave/MEX
kernels (getada{1,2,3}.c), run through the exact pre-loop Aord/DAt setup
and main-loop call sequence sedumi.m uses.

Oracle data (tests/fixtures/getada/*.mat) is generated by
tools/generate_getada_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy._native import getada1, getada2, getada3  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "getada"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="getada fixtures not generated"
)


def _ravel(x):
    return np.asarray(x).ravel()


def _load(name: str):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    A = sp.csc_matrix(data["A"])
    m = A.shape[1]

    Ablkjc = data["Ablkjc"].astype(np.int64)
    Ajc = Ablkjc[:, 2]

    K = {
        "l": float(_ravel(data["Kl"])[0]),
        "q": _ravel(data["Kq"]),
        "s": _ravel(data["Ks"]),
    }
    K["blkstart"] = _ravel(data["blkstart"])
    K["qblkstart"] = _ravel(data["qblkstart"])

    d = {"l": _ravel(data["d_l"]), "det": _ravel(data["d_det"])}

    DAt_q = data["DAt_q"]
    DAt = {"q": sp.csc_matrix(DAt_q) if DAt_q.size else sp.csc_matrix((0, m))}

    Aord = {
        "lqperm": _ravel(data["lqperm"]),
        "qperm": _ravel(data["qperm"]),
        "sperm": _ravel(data["sperm"]),
        "dz": sp.csc_matrix(data["dz"]),
    }

    udsqr = _ravel(data["udsqr"])

    ADA0 = sp.csc_matrix(data["ADA0"])
    ADA1_expected = sp.csc_matrix(data["ADA1"])
    ADA2_expected = sp.csc_matrix(data["ADA2"])
    ADA3_expected = sp.csc_matrix(data["ADA3"])
    absd_expected = _ravel(data["absd"])

    return dict(
        A=A, Ajc=Ajc, K=K, d=d, DAt=DAt, Aord=Aord, udsqr=udsqr,
        ADA0=ADA0, ADA1_expected=ADA1_expected, ADA2_expected=ADA2_expected,
        ADA3_expected=ADA3_expected, absd_expected=absd_expected,
    )


def _run_case(name: str):
    c = _load(name)

    ADA1 = getada1(c["ADA0"], c["A"], c["Ajc"], c["Aord"]["lqperm"], c["d"], c["K"]["qblkstart"])
    np.testing.assert_allclose(ADA1.toarray(), c["ADA1_expected"].toarray())

    ADA2 = getada2(ADA1, c["DAt"], c["Aord"], c["K"])
    np.testing.assert_allclose(ADA2.toarray(), c["ADA2_expected"].toarray())

    ADA3, absd = getada3(ADA2, c["A"], c["Ajc"], c["Aord"], c["udsqr"], c["K"])
    np.testing.assert_allclose(ADA3.toarray(), c["ADA3_expected"].toarray())
    np.testing.assert_allclose(absd, c["absd_expected"])


def test_getada_lorentz_and_one_psd_block():
    _run_case("case1")


def test_getada_two_lorentz_two_psd_blocks():
    _run_case("case2")


def test_getada_no_lorentz_cones():
    _run_case("case3")


def test_getada_no_psd_blocks():
    _run_case("case4")
