"""Verify _native.adenscale against the real Octave/MEX adenscale.

Oracle data (tests/fixtures/adenscale/*.mat) is generated by
tools/generate_adenscale_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "adenscale"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="adenscale fixtures not generated"
)


def _run_case(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    dense = {
        "l": int(data["dense_l"].item()),
        "q": data["dense_q"].ravel().astype(np.int64),
        "cols": data["dense_cols"].ravel().astype(np.int64),
    }
    d = {"det": data["d_det"].ravel().astype(np.float64)}
    qblkstart = data["qblkstart"].ravel().astype(np.int64)
    expected = data["smult"].ravel().astype(np.float64)

    got = _native.adenscale(dense, d, qblkstart)

    np.testing.assert_allclose(got, expected)


def test_adenscale_two_dense_lorentz_blocks():
    _run_case("case1")


def test_adenscale_single_dense_lorentz_block():
    _run_case("case2")


def test_adenscale_no_dense_normbound_columns():
    _run_case("case3")
