"""Phase 2 cluster 5 (partial): verify sortnnz, cholsplit, finsymbden,
mJdetd against the real Octave/MEX build (mJdetd is dead code -- see
below -- so it gets an independent math check instead of an oracle one).

Scope note: incorder, iswnbr, symbfwblk are NOT covered here -- like
getada1/getada2/getada3/adendotd/adenscale from cluster 4, they are
deeply tied to sedumi.m's internal "dense columns" bookkeeping and are
deferred to Phase 3 (see the cluster 4/5 scope discussion raised with
the user).

Oracle data (tests/fixtures/cluster5/*.mat, plus reused cluster2
dpr1fact fixtures for finsymbden) is generated by
tools/generate_cluster5_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cluster5"
CLUSTER2_DIR = Path(__file__).parent / "fixtures" / "cluster2"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cluster5 fixtures not generated"
)


def test_sortnnz_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "sortnnz.mat")
    got = _native.sortnnz(data["At"].tocsc())
    np.testing.assert_array_equal(got, data["perm"].ravel())


def test_cholsplit_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "cholsplit.mat")
    Lstruct = data["L"][0, 0]
    L = {"L": Lstruct["L"].tocsc(), "xsuper": Lstruct["xsuper"].ravel()}
    got = _native.cholsplit(L, float(data["cachesizeKB"].item()))
    np.testing.assert_array_equal(got, data["split"].ravel())


@pytest.mark.skipif(
    not (CLUSTER2_DIR / "dpr1fact_n1.mat").exists(), reason="cluster2 fixtures missing"
)
@pytest.mark.parametrize("case", ["dpr1fact_n1", "dpr1fact_n2"])
def test_finsymbden_matches_octave_mex(case):
    data = scipy.io.loadmat(CLUSTER2_DIR / f"{case}.mat")
    Lden_oracle = data["Lden"][0, 0]

    Lsym = _native.finsymbden(
        data["LAD"].tocsc(), data["perm"].ravel(), data["dz"].tocsc(),
        int(data["firstq"].item()),
    )
    np.testing.assert_array_equal(Lsym["perm"], Lden_oracle["perm"].ravel())
    np.testing.assert_array_equal(Lsym["first"], Lden_oracle["first"].ravel())
    np.testing.assert_array_equal(Lsym["dz"].toarray(), data["dz"].tocsc().toarray())


def test_mJdetd_matches_direct_formula():
    """mJdetd.c is dead code (not in install_sedumi.m's target list, no
    mJdetd.m wrapper, no .m file calls it) -- like blkmul.c (cluster 1)
    and bwblkslv2.c (Phase 1). No real MEX build exists to check
    against, so this checks the documented formula directly instead:
    y[block k] = [-detd(k); detd(k)*ones(nk-1,1)]."""
    K = {"q": [3, 4]}
    detd = np.array([2.0, 5.0])
    y = _native.mJdetd(detd, K)
    expected = np.concatenate([[-2.0, 2.0, 2.0], [-5.0, 5.0, 5.0, 5.0]])
    np.testing.assert_array_equal(y, expected)
