"""Phase 3-c: verify sdfactor.py and sddir.py against the real Octave
build, using the same mixed L+Lorentz+real-SDP problem/scaling
point/ADA factorization as the recent pcg.py fixtures.

Oracle data (tests/fixtures/sdinit/sddir.mat) is generated by
tools/generate_sddir_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.sddir import sddir  # noqa: E402
from sedumipy.sdfactor import sdfactor  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "sddir.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    DAtmat = data["DAt"][0, 0]
    q = DAtmat["q"]
    DAt = {"q": np.asarray(q.todense() if sp.issparse(q) else q)}
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "q": densemat["q"].ravel()}
    Lmat = data["Lstruct"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
        "perm": Lmat["perm"].ravel().astype(np.int64) - 1,
    }
    Lden = {"betajc": np.array([1])}
    At2 = sp.csc_matrix(data["At2"])
    c2 = _densify(data["c2"])
    b2 = _densify(data["b2"])
    v = data["v"].ravel()
    y = data["y"].ravel()
    y0 = float(data["y0"].item())
    Rmat = data["R"][0, 0]
    R = {fld: (Rmat[fld].ravel() if Rmat[fld].size > 1 else float(Rmat[fld].item())) for fld in Rmat.dtype.names}
    vfrmmat = data["vfrm"][0, 0]
    vfrm = {fld: vfrmmat[fld].ravel() for fld in vfrmmat.dtype.names}
    parsmat = data["pars"][0, 0]
    cgmat = parsmat["cg"][0, 0]
    cg = {fld: float(cgmat[fld].item()) for fld in cgmat.dtype.names}
    pars = {"cg": cg}
    perm = Lmat["perm"].ravel().astype(np.int64) - 1
    assert np.array_equal(perm, np.arange(perm.size)), "test assumes identity L.perm (see pcg tests)"
    return data, K, d, DAt, dense, L, Lden, At2, c2, b2, v, y, y0, R, vfrm, pars


def test_sdfactor_matches_octave():
    data, K, d, DAt, dense, L, Lden, At2, c2, b2, v, y, y0, R, vfrm, pars = _load()
    Lsd = sdfactor(L, Lden, dense, DAt, d, v, y, At2, c2, K, R, y0, pars)

    Lsd_exp = data["Lsd"][0, 0]
    np.testing.assert_allclose(Lsd["DRc"], Lsd_exp["DRc"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(Lsd["y"], Lsd_exp["y"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(Lsd["x"], Lsd_exp["x"].ravel(), rtol=1e-6, atol=1e-8)
    assert Lsd["kcg"] == int(Lsd_exp["kcg"].item())
    np.testing.assert_allclose(Lsd["b"], Lsd_exp["b"].ravel(), rtol=1e-6, atol=1e-8)
    assert Lsd["denom"] == pytest.approx(float(Lsd_exp["denom"].item()), rel=1e-6)


def _lsd_dict(data):
    Lsd_exp = data["Lsd"][0, 0]
    return {fld: Lsd_exp[fld].ravel() if Lsd_exp[fld].size > 1 else float(Lsd_exp[fld].item())
            for fld in Lsd_exp.dtype.names}


@pytest.mark.parametrize("pmode,suffix", [(1, "1"), (2, "2"), (3, "3")])
def test_sddir_matches_octave(pmode, suffix):
    data, K, d, DAt, dense, L, Lden, At2, c2, b2, v, y, y0, R, vfrm, pars = _load()
    Lsd = _lsd_dict(data)

    if pmode == 1:
        pv = data["pv1"].ravel()
    elif pmode == 2:
        pv = None
    else:
        pv = data["pv3"].ravel()

    dx, dy, dz, dy0, err = sddir(
        L, Lden, Lsd, pv, d, v, vfrm, At2, DAt, dense, R, K, y, y0, b2, pars, pmode
    )

    np.testing.assert_allclose(dx, data[f"dx{suffix}"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(dy, data[f"dy{suffix}"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(dz, data[f"dz{suffix}"].ravel(), rtol=1e-6, atol=1e-8)
    assert dy0 == pytest.approx(float(data[f"dy0{suffix}"].item()), rel=1e-6)

    err_exp = data[f"err{suffix}"][0, 0]
    assert err["kcg"] == int(err_exp["kcg"].item())
    np.testing.assert_allclose(err["b"], err_exp["b"].ravel(), rtol=1e-6, atol=1e-8)
    assert err["maxb"] == pytest.approx(float(err_exp["maxb"].item()), rel=1e-6)
