"""Phase 3-c: verify trydif.py against the real Octave build, covering
both branches (trial point kept when wr.delta <= pars.beta; falls back
to t=0/wIN/wrIN otherwise), using the same mixed L+Lorentz+real-SDP
problem as the recent maxstep/updtransfo fixtures.

Oracle data (tests/fixtures/sdinit/trydif.mat) is generated by
tools/generate_trydif_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.trydif import trydif  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _struct_dict(mat):
    return {fld: (mat[fld].ravel() if mat[fld].size > 1 else float(mat[fld].item()))
            for fld in mat.dtype.names}


def test_trydif_keeps_trial_point():
    data = scipy.io.loadmat(FIXTURE_DIR / "trydif.mat")
    K = _load_K(data["K2"][0, 0])
    pars = {"theta": 0.25, "beta": 0.5}
    wrIN = _struct_dict(data["wrIN1"][0, 0])
    wIN = {}
    x1 = data["x1"].ravel()
    z1 = data["z1"].ravel()
    t1 = float(data["t1"].item())

    t_out, wr, w = trydif(t1, wrIN, wIN, x1, z1, pars, K)

    assert t_out == pytest.approx(float(data["t1_out"].item()), rel=1e-8)
    wr_exp = _struct_dict(data["wr1"][0, 0])
    for fld in ("delta", "h", "alpha", "desc"):
        assert wr[fld] == pytest.approx(wr_exp[fld], rel=1e-6, abs=1e-9)

    w_exp = data["w1"][0, 0]
    np.testing.assert_allclose(w["lab"], w_exp["lab"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["tdetx"], w_exp["tdetx"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["ux"], w_exp["ux"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["s"], w_exp["s"].ravel(), rtol=1e-6, atol=1e-8)


def test_trydif_falls_back_to_previous_point():
    data = scipy.io.loadmat(FIXTURE_DIR / "trydif.mat")
    K = _load_K(data["K2"][0, 0])
    pars = {"theta": 0.25, "beta": 0.5}
    wrIN = _struct_dict(data["wrIN2"][0, 0])
    wINmat = data["wIN2"][0, 0]
    wIN = {fld: wINmat[fld].ravel() for fld in wINmat.dtype.names}
    x2 = data["x2"].ravel()
    z2 = data["z2"].ravel()
    t2 = float(data["t2"].item())

    t_out, wr, w = trydif(t2, wrIN, wIN, x2, z2, pars, K)

    assert t_out == 0.0
    assert wr["delta"] == pytest.approx(wrIN["delta"])
    assert wr["h"] == pytest.approx(wrIN["h"])
    assert wr["alpha"] == pytest.approx(wrIN["alpha"])
    np.testing.assert_array_equal(w["lab"], wIN["lab"])
