"""Verify getada_psd.build_aord/getada_psd against the real Octave/MEX
pipeline, run exactly as sedumi.m's own pre-loop setup (Ablkjc/Aord/
getsymbada) and main-loop getada1->getada2->getada3 (with real
invcholfac(), not a fabricated udsqr) do.

Oracle data (tests/fixtures/getada_psd/*.mat) is generated by
tools/generate_getada_psd_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.getada_psd import build_aord, getada_psd  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "getada_psd"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="getada_psd fixtures not generated"
)


def _ravel(x):
    return np.asarray(x).ravel()


def _run_case(name: str):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    A = sp.csc_matrix(data["A"])
    m = A.shape[1]

    K = {
        "l": float(_ravel(data["Kl"])[0]),
        "q": _ravel(data["Kq"]),
        "s": _ravel(data["Ks"]),
        "mainblks": _ravel(data["mainblks"]),
        "qblkstart": _ravel(data["qblkstart"]),
        "sblkstart": _ravel(data["sblkstart"]),
        "blkstart": _ravel(data["blkstart"]),
    }

    Ablkjc_expected = data["Ablkjc"].astype(np.int64)
    symbada_expected = sp.csc_matrix(data["SYMBADA"])

    Ablkjc, Aord, symbada = build_aord(A, K)
    np.testing.assert_array_equal(Ablkjc, Ablkjc_expected)
    np.testing.assert_array_equal(_ravel(Aord["lqperm"]), _ravel(data["lqperm"]))
    np.testing.assert_array_equal(_ravel(Aord["qperm"]), _ravel(data["qperm"]))
    np.testing.assert_array_equal(_ravel(Aord["sperm"]), _ravel(data["sperm"]))
    np.testing.assert_allclose(Aord["dz"].toarray(), sp.csc_matrix(data["dz"]).toarray())
    np.testing.assert_allclose(symbada.toarray(), symbada_expected.toarray())

    d = {"l": _ravel(data["d_l"]), "det": _ravel(data["d_det"]), "u": _ravel(data["d_u"]), "perm": np.zeros(0)}
    DAt_q = data["DAt_q"]
    DAt = {"q": sp.csc_matrix(DAt_q) if DAt_q.size else sp.csc_matrix((0, m))}

    ADA0 = symbada
    ADA3, absd = getada_psd(ADA0, A, Ablkjc, Aord, DAt, d, K)

    np.testing.assert_allclose(ADA3.toarray(), sp.csc_matrix(data["ADA3"]).toarray())
    np.testing.assert_allclose(absd, _ravel(data["absd"]))


def test_getada_psd_lorentz_and_one_psd_block():
    _run_case("case1")


def test_getada_psd_two_lorentz_two_psd_blocks():
    _run_case("case2")


def test_getada_psd_no_lorentz_cones():
    _run_case("case3")
