"""Verify getsymbada.getsymbada against the real Octave/MEX pipeline
(getsymbada.m + its partitA/findblks/extractA dependencies), run exactly
as sedumi.m's own pre-main-loop setup does.

Oracle data (tests/fixtures/getsymbada/*.mat) is generated by
tools/generate_getsymbada_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy._native import partitA  # noqa: E402
from sedumipy.getsymbada import getsymbada  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "getsymbada"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="getsymbada fixtures not generated"
)


def _to_sparse_pattern(mat_entry, nrows: int, ncols: int):
    """Octave saves an empty `q_pattern` (no Lorentz cones) as a 0x0
    double; reshape it to the expected `nrows x ncols` all-zero sparse
    matrix so callers see a consistent shape regardless of `nrows`.
    """
    if mat_entry.size == 0:
        return sp.csc_matrix((nrows, ncols))
    return sp.csc_matrix(mat_entry)


def _run_case(name: str):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    A = sp.csc_matrix(data["A"])
    mainblks = data["mainblks"].ravel().astype(np.int64)
    sblkstart = data["sblkstart"].ravel().astype(np.int64)
    Ablkjc_expected = data["Ablkjc"].astype(np.int64)
    symbada_expected = sp.csc_matrix(data["SYMBADA"])

    m = A.shape[1]
    q_pattern = _to_sparse_pattern(data["q_pattern"], data["q_pattern"].shape[0], m)

    Ablkjc = partitA(A, mainblks)
    np.testing.assert_array_equal(Ablkjc, Ablkjc_expected)

    symbada = getsymbada(A, Ablkjc, q_pattern if q_pattern.shape[0] else None, sblkstart)
    np.testing.assert_allclose(symbada.toarray(), symbada_expected.toarray())


def test_getsymbada_lorentz_and_one_psd_block():
    _run_case("case1")


def test_getsymbada_two_lorentz_two_psd_blocks():
    _run_case("case2")


def test_getsymbada_dense_fallback():
    _run_case("case3")


def test_getsymbada_no_lorentz_cones():
    _run_case("case4")
