"""Phase 3-c: verify wregion.py against the real Octave build, using
the same mixed L+Lorentz+real-SDP problem/ADA factorization as the
recent pcg/sddir fixtures, covering both wr.delta==0 (no initial
centering -- the real first-iteration state) and wr.delta>0 (initial
centering path), and both pars.stepdif==1 (stepdif+trydif 2nd
correction) and pars.stepdif!=1 (skipped).

Oracle data (tests/fixtures/sdinit/wregion_case*.mat) is generated by
tools/generate_wregion_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.wregion import wregion  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


def _struct_dict(mat):
    out = {}
    for fld in mat.dtype.names:
        val = mat[fld]
        out[fld] = val.ravel() if val.size > 1 else float(val.item())
    return out


def _load(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    DAtmat = data["DAt"][0, 0]
    q = DAtmat["q"]
    DAt = {"q": np.asarray(q.todense() if sp.issparse(q) else q)}
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "q": densemat["q"].ravel()}
    Lmat = data["Lstruct"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
        "perm": Lmat["perm"].ravel().astype(np.int64) - 1,
    }
    perm = L["perm"]
    assert np.array_equal(perm, np.arange(perm.size)), "test assumes identity L.perm"
    Lden = {"betajc": np.array([1])}
    At2 = sp.csc_matrix(data["At2"])
    v = data["v"].ravel()
    y = data["y"].ravel()
    y0 = float(data["y0"].item())
    b2 = _densify(data["b2"])
    Rmat = data["R"][0, 0]
    R = {fld: (Rmat[fld].ravel() if Rmat[fld].size > 1 else float(Rmat[fld].item())) for fld in Rmat.dtype.names}
    vfrmmat = data["vfrm"][0, 0]
    vfrm = {fld: vfrmmat[fld].ravel() for fld in vfrmmat.dtype.names}
    parsmat = data["pars"][0, 0]
    cgmat = parsmat["cg"][0, 0]
    cg = {fld: float(cgmat[fld].item()) for fld in cgmat.dtype.names}
    pars = {
        "cg": cg,
        "alg": int(parsmat["alg"].item()),
        "beta": float(parsmat["beta"].item()),
        "theta": float(parsmat["theta"].item()),
        "stepdif": int(parsmat["stepdif"].item()),
    }
    wr = _struct_dict(data["wr"][0, 0])
    Lsdmat = data["Lsd"][0, 0]
    Lsd = {fld: (Lsdmat[fld].ravel() if Lsdmat[fld].size > 1 else float(Lsdmat[fld].item())) for fld in Lsdmat.dtype.names}
    return data, K, d, DAt, dense, L, Lden, Lsd, At2, v, y, y0, b2, R, vfrm, pars, wr


@pytest.mark.parametrize("name", ["wregion_case1", "wregion_case2"])
def test_wregion_matches_octave(name):
    data, K, d, DAt, dense, L, Lden, Lsd, At2, v, y, y0, b2, R, vfrm, pars, wr = _load(name)

    xscl, yout, zscl, y0out, w, relt, dxmdz, err, wrout = wregion(
        L, Lden, Lsd, d, v, vfrm, At2, DAt, dense, R, K, y, y0, b2, pars, wr
    )

    np.testing.assert_allclose(xscl, data["xscl"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(yout, data["yout"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(zscl, data["zscl"].ravel(), rtol=1e-6, atol=1e-8)
    assert y0out == pytest.approx(float(data["y0out"].item()), rel=1e-6)
    np.testing.assert_allclose(dxmdz, data["dxmdz"].ravel(), rtol=1e-6, atol=1e-8)

    relt_exp = _struct_dict(data["relt"][0, 0])
    assert relt["p"] == pytest.approx(relt_exp["p"], rel=1e-6)
    assert relt["d"] == pytest.approx(relt_exp["d"], rel=1e-6)

    err_exp = data["err"][0, 0]
    np.testing.assert_allclose(err["b"], _densify(err_exp["b"]), rtol=1e-6, atol=1e-8)
    assert err["db0"] == pytest.approx(float(err_exp["db0"].item()), rel=1e-5, abs=1e-8)
    assert err["g"] == pytest.approx(float(err_exp["g"].item()), rel=1e-6, abs=1e-9)
    assert err["maxb"] == pytest.approx(float(err_exp["maxb"].item()), rel=1e-6, abs=1e-9)

    wr_exp = _struct_dict(data["wrout"][0, 0])
    assert wrout["delta"] == pytest.approx(wr_exp["delta"], rel=1e-6, abs=1e-9)
    assert wrout["h"] == pytest.approx(wr_exp["h"], rel=1e-6)
    assert wrout["alpha"] == pytest.approx(wr_exp["alpha"], rel=1e-6)
    assert wrout["tpmtd"] == pytest.approx(wr_exp["tpmtd"], rel=1e-6, abs=1e-9)

    w_exp = data["w"][0, 0]
    np.testing.assert_allclose(w["lab"], w_exp["lab"].ravel(), rtol=1e-6, atol=1e-8)
