"""Phase 3-c: verify widelen.py against the real Octave build, using the
same mixed L+Lorentz+real-SDP problem as the recent trydif/maxstep
fixtures, with a genuine interior point and descent direction that
exercises several bisection iterations (t converges to neither 0 nor
maxt).

Oracle data (tests/fixtures/sdinit/widelen.mat) is generated by
tools/generate_widelen_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.widelen import widelen  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_widelen_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "widelen.mat")
    K = _load_K(data["K2"][0, 0])
    parsmat = data["pars"][0, 0]
    pars = {"theta": float(parsmat["theta"].item()), "beta": float(parsmat["beta"].item())}

    xc = data["xc"].ravel()
    zc = data["zc"].ravel()
    dx = data["dx"].ravel()
    dz = data["dz"].ravel()
    y0 = float(data["y0"].item())
    dy0 = float(data["dy0"].item())
    d2y0 = float(data["d2y0"].item())
    maxt = float(data["maxt"].item())

    t, wr, w = widelen(xc, zc, y0, dx, dz, dy0, d2y0, maxt, pars, K)

    assert t == pytest.approx(float(data["t"].item()), rel=1e-8)
    # Confirm this fixture actually exercises the bisection loop (not a
    # trivial t=0 or t=maxt edge case).
    assert 0 < t < maxt

    wr_exp = data["wr"][0, 0]
    for fld in ("delta", "h", "alpha", "desc"):
        assert wr[fld] == pytest.approx(float(wr_exp[fld].item()), rel=1e-6, abs=1e-9)

    w_exp = data["w"][0, 0]
    np.testing.assert_allclose(w["lab"], w_exp["lab"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["tdetx"], w_exp["tdetx"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["ux"], w_exp["ux"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(w["s"], w_exp["s"].ravel(), rtol=1e-6, atol=1e-8)
