"""Phase 3-d: golden-reference, end-to-end verification of sedumi.py
(the top-level driver) against the real Octave sedumi.m, on small LP,
SOCP (Lorentz), and PSD (K.s) problems -- covering primal-dual optimal
solutions as well as the dual-infeasible-with-improving-direction
outcome.

Oracle data (tests/fixtures/sedumi/*.mat) is generated by
tools/generate_sedumi_oracle.m and committed, so this test
does not require Octave to be installed to run.

`lp_socp_sdp_dense_feasible` (generated by
tools/generate_sedumi_dense_oracle.m, Stage 8 of the dense-columns
optimization plan) is the one end-to-end case that actually exercises
the whole dense-column pipeline together -- getdense() detection, the
one-time A(dense.cols,:)=0.0 zeroing, symbcholden(), and
getdatm.py/getada_psd.py/deninfac.py/pcg.py's per-iteration product-form
correction -- rather than each piece in isolation. Its pars.denf=3
override (checkpars.py's default is 10) is what makes getdense()'s
heuristic actually fire on a problem this small, so unlike every other
case here it must be passed into sedumi() explicitly rather than relying
on defaults.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.sedumi import sedumi  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sedumi"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sedumi fixtures not generated"
)


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld in ("f", "l"):
            K[fld] = int(val.item())
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


@pytest.mark.parametrize(
    "name",
    [
        "lp_feasible",
        "lp_free_feasible",
        "socp_feasible",
        "socp_two_blocks",
        "lp_infeasible",
        "rotated_cone_feasible",
        "lp_sparse_feasible",
        "sdp_feasible",
        "sdp_mixed_cones_feasible",
    ],
)
def test_sedumi_matches_octave(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    At = sp.csc_matrix(data["At"])
    b = _densify(data["b"])
    c = _densify(data["c"])
    K = _load_K(data["K"][0, 0])
    info_oct = data["info"][0, 0]

    x, y, info = sedumi(At, b, c, K)

    assert info["iter"] == int(info_oct["iter"].item())
    assert info["numerr"] == int(info_oct["numerr"].item())
    assert info["pinf"] == int(info_oct["pinf"].item())
    assert info["dinf"] == int(info_oct["dinf"].item())

    np.testing.assert_allclose(x, _densify(data["x"]), rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(y, _densify(data["y"]), rtol=1e-5, atol=1e-6)


def _load_pars(parsmat):
    pars = {}
    for fld in parsmat.dtype.names:
        pars[fld] = parsmat[fld].item()
    return pars


def test_sedumi_dense_matches_octave():
    """`lp_socp_sdp_dense_feasible`'s At (23x20) has rank only 16: its PSD
    block's extra-sparse background rows are sparse enough that some are
    structurally all-zero regardless of random seed (confirmed by sweeping
    seeds 1-400 -- none reach full row rank), and that sparsity is exactly
    what lets getdense.m's detection heuristic fire on a problem this small
    in the first place. A rank-deficient At makes the dual solution y
    non-unique: any y' = y + delta with At@delta==0 is an equally valid
    optimal dual (same slack s=c-At@y, same objective b@y). Python's and
    Octave's y do differ (~5 in 2-norm) along exactly this degenerate
    null-space direction -- verified via At@(y_py-y_oct) ~ 1e-7 and
    b@(y_py-y_oct) ~ 1e-9, both effectively 0 -- even though iter/numerr/
    pinf/dinf match exactly and x matches to ~1e-9, i.e. the algorithm
    runs identically and it's the problem's dual that's ill-posed. So this
    test compares dual feasibility/optimality (the induced slack and
    objective) instead of raw y equality, unlike every other case here.
    """
    name = "lp_socp_sdp_dense_feasible"
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    At = sp.csc_matrix(data["At"])
    b = _densify(data["b"])
    c = _densify(data["c"])
    K = _load_K(data["K"][0, 0])
    pars = _load_pars(data["pars"][0, 0])
    info_oct = data["info"][0, 0]

    x, y, info = sedumi(At, b, c, K, pars)

    assert info["iter"] == int(info_oct["iter"].item())
    assert info["numerr"] == int(info_oct["numerr"].item())
    assert info["pinf"] == int(info_oct["pinf"].item())
    assert info["dinf"] == int(info_oct["dinf"].item())

    np.testing.assert_allclose(x, _densify(data["x"]), rtol=1e-5, atol=1e-6)

    y_exp = _densify(data["y"])
    np.testing.assert_allclose(c - At @ y, c - At @ y_exp, rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(float(b @ y), float(b @ y_exp), rtol=1e-5, atol=1e-6)
