"""Verify _native.adendotd against the real Octave/MEX adendotd.

Oracle data (tests/fixtures/adendotd/*.mat) is generated by
tools/generate_adendotd_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "adendotd"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="adendotd fixtures not generated"
)


def _run_case(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    dense = {
        "l": int(data["dense_l"].item()),
        "q": data["dense_q"].ravel().astype(np.int64),
        "cols": data["dense_cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix(data["dense_A"]),
    }
    d = {
        "q1": data["d_q1"].ravel().astype(np.float64),
        "q2": data["d_q2"].ravel().astype(np.float64),
    }
    adotd = sp.csc_matrix(data["sparAd"])
    ablk = sp.csc_matrix(data["Ablk"])
    qblkstart = data["qblkstart"].ravel().astype(np.int64)
    expected = np.asarray(data["Ad"].todense())

    got = _native.adendotd(dense, d, adotd, ablk, qblkstart)

    assert got.shape == expected.shape
    np.testing.assert_allclose(np.asarray(got.todense()), expected)


def test_adendotd_single_dense_lorentz_block():
    _run_case("case1")


def test_adendotd_two_dense_lorentz_blocks_partial_ablk():
    _run_case("case2")
