"""Phase 3-c: verify PopK (cone.py) against the real Octave build.

Oracle data (tests/fixtures/sdinit/popk.mat) is generated by
tools/generate_popk_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import cone  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_popk_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "popk.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    x = data["x"].ravel()

    y, ddotx, Dx, xTy = cone.PopK(d, x, K)
    np.testing.assert_allclose(y, data["y_full"].ravel(), rtol=1e-9, atol=1e-11)
    np.testing.assert_allclose(ddotx, data["ddotx_full"].ravel(), rtol=1e-9, atol=1e-11)
    np.testing.assert_allclose(Dx, data["Dx_full"].ravel(), rtol=1e-9, atol=1e-11)
    assert xTy == pytest.approx(float(data["xTy_full"].item()), rel=1e-8)

    y_lpq, _, _, _ = cone.PopK(d, x, K, lpq=True)
    np.testing.assert_allclose(y_lpq, data["y_lpq"].ravel(), rtol=1e-9, atol=1e-11)
