"""Phase 3-c: verify stepdif.py against the real Octave build across
several hand-built scenarios covering its many sign-dependent branches
(tpmtd sign, R.sd sign/zero, usegap).

Oracle data (tests/fixtures/stepdif/*.mat) is generated by
tools/generate_stepdif_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.stepdif import stepdif  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "stepdif"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="stepdif fixtures not generated"
)

CASES = [
    "case1_tpmtd_pos_sdpos",
    "case2_tpmtd_neg_sdpos",
    "case3_sdneg",
    "case4_sdzero",
    "case5_large_step",
    "case6_large_step_neg_tpmtd",
    "case7_interior_minimizer",
    "case8_breakpoint",
]


@pytest.mark.parametrize("name", CASES)
def test_stepdif_matches_octave(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    dmat = data["d"][0, 0]
    d = {"l": dmat["l"].ravel()}
    Rmat = data["R"][0, 0]
    R = {"sd": float(Rmat["sd"].item()), "b0": float(Rmat["b0"].item()), "w": Rmat["w"].ravel()}

    y0 = float(data["y0"].item())
    x = data["x"].ravel()
    y = data["y"].ravel()
    z = data["z"].ravel()
    dy0 = float(data["dy0"].item())
    dx = data["dx"].ravel()
    dy = data["dy"].ravel()
    dz = data["dz"].ravel()
    b = data["b"].ravel()
    mint = float(data["mint"].item())
    tpmtd = float(data["tpmtd"].item())

    t, rcdx = stepdif(d, R, y0, x, y, z, dy0, dx, dy, dz, b, mint, tpmtd)

    assert t == pytest.approx(float(data["t"].item()), rel=1e-8)
    assert rcdx == pytest.approx(float(data["rcdx"].item()), rel=1e-8)
