"""Phase 3-b/3-c: verify tdet and asmDxq (cone.py) against the real
Octave build, using a genuine scaling-point struct `d` from sdinit.m
(these two were deferred from Phase 3-b's cone-math batch precisely
because they need such a `d`, which didn't exist yet at that point).

Oracle data (tests/fixtures/sdinit/tdet_asmdxq.mat) is generated by
tools/generate_tdet_asmdxq_oracle.m and committed, so this
test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import cone  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "tdet_asmdxq.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    return data, K, d


def test_tdet_matches_octave():
    data, K, d = _load()
    got = cone.tdet(data["x"].ravel(), K)
    np.testing.assert_allclose(got, data["tdetx"].ravel(), rtol=1e-9, atol=1e-11)


def test_asmdxq_two_output_matches_octave():
    data, K, d = _load()
    y, t = cone.asmDxq(d, data["x"].ravel(), K, want_t=True)
    np.testing.assert_allclose(y, data["y_asm2"].ravel(), rtol=1e-9, atol=1e-11)
    np.testing.assert_allclose(t, data["t_asm2"].ravel(), rtol=1e-9, atol=1e-11)


def test_asmdxq_single_output_matches_octave():
    data, K, d = _load()
    y = cone.asmDxq(d, data["x"].ravel(), K)
    np.testing.assert_allclose(y, data["y_asm1"].ravel(), rtol=1e-9, atol=1e-11)


def test_asmdxq_precomputed_ddotx_matches_octave():
    data, K, d = _load()
    y = cone.asmDxq(d, data["x"].ravel(), K, ddotx=data["ddotx_precomputed"].ravel())
    np.testing.assert_allclose(y, data["y_asm_ddotx"].ravel(), rtol=1e-9, atol=1e-11)


def test_asmdxq_qonly_matches_octave():
    data, K, d = _load()
    y, t = cone.asmDxq(d, data["x_qonly"].ravel(), K, want_t=True)
    np.testing.assert_allclose(y, data["y_asm_qonly"].ravel(), rtol=1e-9, atol=1e-11)
    np.testing.assert_allclose(t, data["t_asm_qonly"].ravel(), rtol=1e-9, atol=1e-11)
