"""Phase 3-b (continued): verify psdeig, psdfactor, psdinvscale, psdjmul,
psdscale, qframeit, qinvjmul, qjmul, frameit, triumtriu (cone.py) against
the real Octave build.

Uses the same internal-format mixed cone as test_cone.py (K.l=2,
K.q=[4;3], K.s=[2;3], K.rsdpN=1), plus the extra bookkeeping fields
(K.mainblks, K.qblkstart, K.sblkstart, K.lq) these files need -- computed
directly from K.l/K.q/K.s (no free vars/rotated cones/split vars, so
pretransfo.m's own formula for these fields reduces to a plain cumsum);
see generate_cone2_oracle.m's docstring for the real-pretransfo
cross-check that confirmed this formula.

Oracle data (tests/fixtures/cone/cone2.mat, cone2_frameit.mat) is
generated by tools/generate_cone2_oracle.m and committed, so
this test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import cone  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cone"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cone fixtures not generated"
)


def _K_from_mat(Kmat):
    K = Kmat[0, 0]
    return {
        "l": int(K["l"].item()),
        "q": K["q"].ravel().tolist(),
        "s": K["s"].ravel().tolist(),
        "rsdpN": int(K["rsdpN"].item()),
        "N": int(K["N"].item()),
        "mainblks": K["mainblks"].ravel(),
        "qblkstart": K["qblkstart"].ravel(),
        "sblkstart": K["sblkstart"].ravel(),
        "lq": int(K["lq"].item()),
    }


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "cone2.mat")
    return data, _K_from_mat(data["K"])


def test_psdeig_lab_matches_octave():
    data, K = _load()
    lab = cone.psdeig(data["x"].ravel(), K)
    np.testing.assert_allclose(lab, data["lab_psd"].ravel(), rtol=1e-10)


def test_psdeig_vectors_reconstruct_x():
    """q's own sign/phase isn't unique, so instead of comparing to the
    oracle directly, check its defining property: X = q*diag(2*lab)*q'
    for each block (q orthogonal/unitary)."""
    data, K = _load()
    x = data["x"].ravel()
    lab, q = cone.psdeig(x, K, want_vectors=True)
    s_sizes = [int(v) for v in K["s"]]
    nr = K["rsdpN"]
    Kq = [ki * ki for ki in s_sizes]
    N = sum(Kq) + sum(Kq[nr:])  # includes the complex-block doubling, unlike psdfactor's plain sum(Ks^2)
    xi = x.size - N
    ei = qi_off = 0
    for i, ki in enumerate(s_sizes):
        qi = ki * ki
        XX = x[xi : xi + qi].copy()
        xi += qi
        if i >= nr:
            XX = XX + 1j * x[xi : xi + qi]
            xi += qi
        XX = (XX.reshape(ki, ki, order="F"))
        XX = XX + XX.conj().T
        QQ = q[qi_off : qi_off + qi].copy()
        qi_off += qi
        if i >= nr:
            QQ = QQ + 1j * q[qi_off : qi_off + qi]
            qi_off += qi
        QQ = QQ.reshape(ki, ki, order="F")
        recon = QQ @ np.diag(2 * lab[ei : ei + ki]) @ QQ.conj().T
        np.testing.assert_allclose(recon, XX, atol=1e-8)
        np.testing.assert_allclose(QQ.conj().T @ QQ, np.eye(ki), atol=1e-8)
        ei += ki


def test_psdfactor_matches_octave():
    data, K = _load()
    ux, ispos = cone.psdfactor(data["x"].ravel(), K)
    assert ispos == bool(data["ispos"].item())
    np.testing.assert_allclose(ux, data["ux"].ravel(), rtol=1e-9, atol=1e-10)


def test_psdinvscale_matches_octave():
    data, K = _load()
    y = cone.psdinvscale(data["ux"].ravel(), data["z"].ravel(), K)
    np.testing.assert_allclose(y, data["y_invscale"].ravel(), rtol=1e-8, atol=1e-9)


def test_psdjmul_matches_octave():
    data, K = _load()
    z = cone.psdjmul(data["x"].ravel(), data["z"].ravel(), K)
    np.testing.assert_allclose(z, data["z_jmul"].ravel(), rtol=1e-10)


def test_psdscale_matches_octave():
    data, K = _load()
    ux = data["ux"].ravel()
    z = data["z"].ravel()
    y0 = cone.psdscale(ux, z, K)
    y1 = cone.psdscale(ux, z, K, transp=True)
    np.testing.assert_allclose(y0, data["y_scale0"].ravel(), rtol=1e-9, atol=1e-10)
    np.testing.assert_allclose(y1, data["y_scale1"].ravel(), rtol=1e-9, atol=1e-10)


def test_psdscale_with_perm_matches_octave():
    data, K = _load()
    ud = {"u": data["ux"].ravel(), "perm": data["perm"].ravel()}
    z = data["z"].ravel()
    y0 = cone.psdscale(ud, z, K)
    y1 = cone.psdscale(ud, z, K, transp=True)
    np.testing.assert_allclose(y0, data["y_scale_perm0"].ravel(), rtol=1e-9, atol=1e-10)
    np.testing.assert_allclose(y1, data["y_scale_perm1"].ravel(), rtol=1e-9, atol=1e-10)


def test_triumtriu_matches_octave():
    data, K = _load()
    z = cone.triumtriu(data["x"].ravel(), data["z"].ravel(), K)
    np.testing.assert_allclose(z, data["z_triumtriu"].ravel(), rtol=1e-10)


def test_qframeit_matches_octave():
    data, K = _load()
    x = cone.qframeit(data["lab_grouped"].ravel(), data["frmq"].ravel(), K)
    np.testing.assert_allclose(x, data["x_qframeit"].ravel(), rtol=1e-10)


def test_qjmul_matches_octave():
    data, K = _load()
    z = cone.qjmul(data["x"].ravel(), data["z"].ravel(), K)
    np.testing.assert_allclose(z, data["z_qjmul"].ravel(), rtol=1e-10)


def test_qinvjmul_matches_octave():
    data, K = _load()
    y = cone.qinvjmul(data["lab_grouped"].ravel(), data["frmq"].ravel(), data["z"].ravel(), K)
    np.testing.assert_allclose(y, data["y_qinvjmul"].ravel(), rtol=1e-8, atol=1e-9)


def test_minpsdeig_matches_octave():
    data, K = _load()
    got = cone.minpsdeig(data["x"].ravel(), K)
    np.testing.assert_allclose(got, float(data["mineig_psd"].item()), rtol=1e-10)


def test_frameit_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "cone2_frameit.mat")
    Kf = data["Kf"][0, 0]
    K = {
        "l": int(Kf["l"].item()),
        "q": Kf["q"].ravel().tolist(),
        "s": Kf["s"].ravel().tolist(),
        "rsdpN": int(Kf["rsdpN"].item()),
        "N": int(Kf["N"].item()),
        "mainblks": Kf["mainblks"].ravel(),
        "qblkstart": Kf["qblkstart"].ravel(),
        "sblkstart": Kf["sblkstart"].ravel(),
        "lq": int(Kf["lq"].item()),
    }
    x = cone.frameit(
        data["labf_grouped"].ravel(), data["frmqf"].ravel(), data["frmsf"].ravel(), K
    )
    np.testing.assert_allclose(x, data["x_frameit"].ravel(), rtol=1e-9, atol=1e-10)
