"""Phase 3-c: verify posttransfo.py against the real Octave build,
reusing the already-committed pretransfo fixtures (for their K2/
prep.QR) across a real-only case, a K.ycomplex case, and a genuinely
complex-QR case (complex SDP block).

Oracle data (tests/fixtures/posttransfo/*.mat) is generated by
tools/generate_posttransfo_oracle.m and committed, so this
test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.posttransfo import posttransfo  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "posttransfo"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="posttransfo fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


@pytest.mark.parametrize("name", ["real_only", "with_ycomplex", "complex_sdp"])
def test_posttransfo_matches_octave(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    K2 = _load_K(data["K2"][0, 0])
    prepmat = data["prep"][0, 0]
    prep = {"QR": prepmat["QR"]}
    x = data["x"].ravel()
    y = data["y"].ravel()

    xp, yp, Kp = posttransfo(x, y, prep, K2)

    np.testing.assert_allclose(xp, _densify(data["xp"]), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(yp, _densify(data["yp"]), rtol=1e-8, atol=1e-10)
    assert Kp["l"] == int(data["Kp"][0, 0]["l"].item())
