"""Phase 3-c: verify checkpars.py against the real Octave build.

Oracle data (tests/fixtures/checkpars/*.mat) is generated by
tools/generate_checkpars_oracle.m and committed, so this
test does not require Octave to be installed to run.
"""

from pathlib import Path

import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.checkpars import checkpars  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "checkpars"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="checkpars fixtures not generated"
)


def _scalar_fields(out):
    names = out.dtype.names
    result = {}
    for name in names:
        val = out[name]
        if name in ("chol", "cg"):
            sub = val[0, 0]
            result[name] = {f: sub[f].item() for f in sub.dtype.names}
        elif name == "w":
            result[name] = val.ravel().tolist()
        else:
            result[name] = val.item()
    return result


def _compare(got: dict, expected: dict):
    for key, exp_val in expected.items():
        assert key in got, f"missing key {key}"
        if isinstance(exp_val, dict):
            _compare(got[key], exp_val)
        elif isinstance(exp_val, list):
            assert list(got[key]) == pytest.approx(exp_val), key
        else:
            assert got[key] == pytest.approx(exp_val), key


def test_checkpars_empty_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "empty.mat")
    expected = _scalar_fields(data["out_empty"][0, 0])
    got = checkpars({})
    _compare(got, expected)


def test_checkpars_partial_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "partial.mat")
    expected = _scalar_fields(data["out_partial"][0, 0])
    got = checkpars({"beta": 0.95, "theta": 0.001, "alg": 5, "eps": 1e-10})
    _compare(got, expected)


def test_checkpars_w_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "w.mat")
    expected = _scalar_fields(data["out_w"][0, 0])
    got = checkpars({"w": [2.5, 1e-10]})
    _compare(got, expected)


def test_checkpars_w_bad_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "w_bad.mat")
    expected = _scalar_fields(data["out_w_bad"][0, 0])
    got = checkpars({"w": [1, 2, 3]})
    _compare(got, expected)


def test_checkpars_nested_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "nested.mat")
    expected = _scalar_fields(data["out_nested"][0, 0])
    got = checkpars({"chol": {"skip": 0}, "cg": {"maxiter": 10}})
    _compare(got, expected)


def test_checkpars_alg0_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "alg0.mat")
    expected = _scalar_fields(data["out_alg0"][0, 0])
    got = checkpars({"alg": 0})
    _compare(got, expected)
