"""Phase 3-c: verify pcg.py (sparfwslv, sparbwslv, loopPcg, wrapPcg)
against the real Octave build, using a genuine A*P(d)*A' system built
from the same mixed L+Lorentz+real-SDP problem/scaling point `d` as the
recent sdinit/getDAtm/PopK fixtures.

Oracle data (tests/fixtures/sdinit/pcg.mat) is generated by
tools/generate_pcg_oracle.m and committed, so this test does
not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.pcg import loopPcg, wrapPcg  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "pcg.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    DAtmat = data["DAt"][0, 0]
    q = DAtmat["q"]
    DAt = {"q": np.asarray(q.todense() if sp.issparse(q) else q)}
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "q": densemat["q"].ravel()}
    Lmat = data["Lstruct"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
        "perm": Lmat["perm"].ravel().astype(np.int64) - 1,
    }
    Lden = {"betajc": np.array([1])}
    At2 = sp.csc_matrix(data["At2"])
    cg = {
        "qprec": 1,
        "restol": 5e-3,
        "stagtol": 5e-14,
        "maxiter": 49,
        "refine": 1,
    }
    return data, K, d, DAt, dense, L, Lden, At2, cg


def test_wrappcg_matches_octave():
    # L.L/L.d (from blkchol) factor ADA(perm,perm), not ADA itself
    # (`ADA(L.perm,L.perm) = L.L*diag(L.d)*L.L'`, per sedumi.m's own
    # comment) -- wrapPcg.m/loopPcg.m never reference L.perm themselves
    # because sparfwslv/sparbwslv (real fwblkslv.c/bwblkslv.c, and this
    # port's pcg.sparfwslv/sparbwslv) apply L.perm internally: sparfwslv
    # gathers its input by L.perm before forward-substituting, sparbwslv
    # scatters its output by L.perm after backward-substituting. So At2/
    # rb/y are passed through in ordinary (real/original) index space,
    # exactly matching sdfactor.py's actual (unpermuted) call to wrapPcg.
    data, K, d, DAt, dense, L, Lden, At2, cg = _load()

    rb = data["rb"].ravel()
    rv = data["rv"].ravel()
    y0 = float(data["y0"].item())
    maxRb = float(data["R"][0, 0]["maxRb"].item())

    y, dx, k, r = wrapPcg(L, Lden, At2, dense, d, DAt, K, rb, rv, cg, min(1, y0) * maxRb)

    y_exp = data["wy"].ravel()
    np.testing.assert_allclose(y, y_exp, rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(dx, data["wdx"].ravel(), rtol=1e-6, atol=1e-8)
    assert k == int(data["wk"].item())


def test_looppcg_matches_octave():
    data, K, d, DAt, dense, L, Lden, At2, cg = _load()

    bvec = data["bvec"].ravel()
    restol = float(data["restol"].item())

    y, k, DAy = loopPcg(L, Lden, At2, dense, d, DAt, K, bvec, None, 0.0, cg, restol)

    y_exp = data["ly"].ravel()
    np.testing.assert_allclose(y, y_exp, rtol=1e-6, atol=1e-8)
    assert k == int(data["lk"].item())
    np.testing.assert_allclose(DAy, data["lDAy"].ravel(), rtol=1e-6, atol=1e-8)


def _load_dense():
    """Same shape as _load(), but for pcg_dense.mat: a genuine nonempty
    dense.cols/dense.q and a real (non-trivial) Lden from deninfac.m --
    exercising loopPcg's new `DAt.denq*DApq(dense.q)` term (Stage 6 of
    the dense-columns optimization plan) end-to-end, rather than the
    trivial no-dense-columns Lden.betajc=1 that _load()'s pcg.mat uses."""
    data = scipy.io.loadmat(FIXTURE_DIR / "pcg_dense.mat")
    K = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    DAtmat = data["DAt"][0, 0]
    q = DAtmat["q"]
    DAt = {
        "q": np.asarray(q.todense() if sp.issparse(q) else q),
        "denq": sp.csc_matrix(DAtmat["denq"]),
    }
    densemat = data["dense"][0, 0]
    dense = {
        "l": int(densemat["l"].item()),
        "q": densemat["q"].ravel().astype(np.int64),
        "cols": densemat["cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix(densemat["A"]),
    }
    Lmat = data["Lstruct"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
        "perm": Lmat["perm"].ravel().astype(np.int64) - 1,
    }
    Ldenmat = data["Ldenstruct"][0, 0]
    Lden = {
        "betajc": Ldenmat["betajc"].ravel().astype(np.int64),
        "beta": Ldenmat["beta"].ravel(),
        "p": Ldenmat["p"].ravel(),
        "dopiv": Ldenmat["dopiv"].ravel().astype(np.int64),
        "pivperm": Ldenmat["pivperm"].ravel().astype(np.int64),
        "dz": sp.csc_matrix(Ldenmat["dz"]),
        "first": Ldenmat["first"].ravel().astype(np.int64),
        "perm": Ldenmat["perm"].ravel().astype(np.int64),
    }
    At2z = sp.csc_matrix(data["At2z"])
    cg = {
        "qprec": 1,
        "restol": 5e-3,
        "stagtol": 5e-14,
        "maxiter": 49,
        "refine": 1,
    }
    return data, K, d, DAt, dense, L, Lden, At2z, cg


def test_wrappcg_dense_matches_octave():
    data, K, d, DAt, dense, L, Lden, At2z, cg = _load_dense()

    rb = data["rb"].ravel()
    rv = data["rv"].ravel()
    y0 = float(data["y0"].item())
    maxRb = float(data["R"][0, 0]["maxRb"].item())

    y, dx, k, r = wrapPcg(L, Lden, At2z, dense, d, DAt, K, rb, rv, cg, min(1, y0) * maxRb)

    y_exp = data["wy"].ravel()
    np.testing.assert_allclose(y, y_exp, rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(dx, data["wdx"].ravel(), rtol=1e-6, atol=1e-8)
    assert k == int(data["wk"].item())


def test_looppcg_dense_matches_octave():
    data, K, d, DAt, dense, L, Lden, At2z, cg = _load_dense()

    bvec = data["bvec"].ravel()
    restol = float(data["restol"].item())

    y, k, DAy = loopPcg(L, Lden, At2z, dense, d, DAt, K, bvec, None, 0.0, cg, restol)

    y_exp = data["ly"].ravel()
    np.testing.assert_allclose(y, y_exp, rtol=1e-6, atol=1e-8)
    assert k == int(data["lk"].item())
    np.testing.assert_allclose(DAy, data["lDAy"].ravel(), rtol=1e-6, atol=1e-8)
