"""Phase 3 (numeric Cholesky, step 2): verify numeric_cholesky()'s
pivot-skip and diagonal-stabilization paths (skip/diagadd), which the
well-conditioned fixtures in test_blkchol.py never exercise.

Mechanism (pinned down by hand-tracing blkchol2.c's cholonBlk() against
a small 3-node example, see the commit message for this file): a column
is *purely skipped* (d=0) when Schur-complement updates from already-
eliminated neighbors push its diagonal to <= 0; it is *stabilized by
adding to the diagonal* instead when the updated diagonal stays small
but positive while some not-yet-eliminated neighbor's coupling in the
same column is disproportionately large (> maxu=500x). Precisely
engineering which one triggers requires knowing ordmmd's elimination
order in advance, which isn't practical by hand -- so the fixtures here
were found by a randomized search
(tests/fixtures/search_blkchol_diagadd2.py) checked against the real
Octave/MEX oracle, then hand-picked to cover: nadd>0 with nskip==0
("pure_add"), nskip>0 with nadd==0 ("pure_skip"), and both at once
("skip_and_add", "skip_and_add2").

The oracle files (tests/fixtures/blkchol_edge/*_oracle.mat) are
generated by tools/generate_blkchol_edge_oracle.m and
committed, so this test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "blkchol_edge"


def _fixture_names():
    if not FIXTURE_DIR.exists():
        return []
    return sorted(
        p.stem for p in FIXTURE_DIR.glob("*.mat") if not p.stem.endswith("_oracle")
    )


@pytest.mark.skipif(not _fixture_names(), reason="blkchol edge fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_skip_and_diagadd_match_octave_mex(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    oracle = scipy.io.loadmat(FIXTURE_DIR / f"{name}_oracle.mat")

    X = data["X"].tocsc()
    perm0 = _native.ordmmd(X)
    sym = _native.symbolic_cholesky(X, perm0)

    expected_perm = np.asarray(oracle["ordmmd_perm"]).squeeze().astype(np.intp) - 1
    np.testing.assert_array_equal(sym["perm"], expected_perm)

    result = _native.numeric_cholesky(sym, X)

    expected_skip = np.sort(np.asarray(oracle["skip_ir"]).ravel().astype(np.int64))
    expected_add = np.sort(np.asarray(oracle["diagadd_ir"]).ravel().astype(np.int64))

    np.testing.assert_array_equal(np.sort(result["skip"]), expected_skip)
    np.testing.assert_array_equal(np.sort(result["diagadd_index"]), expected_add)

    expected_L = oracle["Lvals"].tocsc()
    got_L = result["L"]
    np.testing.assert_array_equal(got_L.indptr, expected_L.indptr)
    np.testing.assert_array_equal(got_L.indices, expected_L.indices)
    np.testing.assert_allclose(got_L.data, expected_L.data, rtol=1e-8, atol=1e-10)

    expected_d = np.asarray(oracle["d"]).squeeze()
    np.testing.assert_allclose(result["d"], expected_d, rtol=1e-8, atol=1e-10)


@pytest.mark.skipif(not _fixture_names(), reason="blkchol edge fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_skipped_pivots_get_unit_column_and_zero_d(name):
    """Independent of the oracle: blkchol.m documents d[skip]=0 and a
    skipped column's L(:,i) becomes e_i (an identity column)."""
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    X = data["X"].tocsc()
    perm0 = _native.ordmmd(X)
    sym = _native.symbolic_cholesky(X, perm0)
    result = _native.numeric_cholesky(sym, X)

    d = result["d"]
    skip = result["skip"]
    assert np.all(d[skip] == 0.0)

    L = result["L"].tocsc()
    for i in skip:
        col = L[:, i].toarray().ravel()
        expected = np.zeros_like(col)
        expected[i] = 1.0
        np.testing.assert_array_equal(col, expected)
