"""Phase 3 (numeric Cholesky, step 1): verify the numeric_cholesky()
ctypes binding (permuteP + spchol/blkLDL in blkchol.c -- the actual
numeric LDL' factorization, as opposed to symfct's symbolic pattern-only
factorization) against the real Octave/MEX symbchol()+blkchol().

Covers only the "happy path" for now (well-conditioned, diagonally
dominant SPD test matrices -- all fixtures have nskip=0, nadd=0 per the
oracle generation log), which is enough to validate permuteP and the
core blkLDL numeric recursion. The skip/diagadd pivot-stabilization path
needs its own follow-up fixtures (an intentionally ill-conditioned or
indefinite matrix) and is not yet covered here.

The oracle files (tests/fixtures/blkchol/*_blkchol_oracle.mat) are
generated by tools/generate_blkchol_oracle.m and committed,
so this test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "blkchol"


def _fixture_names():
    if not FIXTURE_DIR.exists():
        return []
    return sorted(p.stem.replace("_spd", "") for p in FIXTURE_DIR.glob("*_spd.mat"))


@pytest.mark.skipif(not _fixture_names(), reason="blkchol fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_numeric_cholesky_matches_octave_mex(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}_spd.mat")
    oracle = scipy.io.loadmat(FIXTURE_DIR / f"{name}_blkchol_oracle.mat")

    X = data["X"].tocsc()
    m = X.shape[0]

    perm0 = _native.ordmmd(X)
    sym = _native.symbolic_cholesky(X, perm0)

    expected_perm = np.asarray(oracle["ordmmd_perm"]).squeeze().astype(np.intp) - 1
    expected_xsuper = np.asarray(oracle["xsuper"]).squeeze().astype(np.intp) - 1
    np.testing.assert_array_equal(sym["perm"], expected_perm)
    np.testing.assert_array_equal(sym["xsuper"], expected_xsuper)

    result = _native.numeric_cholesky(sym, X)

    assert result["skip"].size == int(np.asarray(oracle["skip_ir"]).size) or (
        oracle["skip_ir"].size == 0 and result["skip"].size == 0
    )
    assert result["diagadd_index"].size == 0
    assert oracle["diagadd_ir"].size == 0

    expected_L = oracle["Lvals"].tocsc()
    got_L = result["L"]
    assert got_L.shape == expected_L.shape
    np.testing.assert_array_equal(got_L.indptr, expected_L.indptr)
    np.testing.assert_array_equal(got_L.indices, expected_L.indices)
    np.testing.assert_allclose(got_L.data, expected_L.data, rtol=1e-10, atol=1e-12)

    expected_d = np.asarray(oracle["d"]).squeeze()
    np.testing.assert_allclose(result["d"], expected_d, rtol=1e-10, atol=1e-12)


@pytest.mark.skipif(not _fixture_names(), reason="blkchol fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_numeric_cholesky_reconstructs_original_matrix(name):
    """Independent of the Octave oracle: L * diag(d) * L' must equal
    X(perm, perm) -- the actual defining property of the factorization,
    checked directly against the input rather than against any reference
    implementation."""
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}_spd.mat")
    X = data["X"].tocsc()

    perm0 = _native.ordmmd(X)
    sym = _native.symbolic_cholesky(X, perm0)
    result = _native.numeric_cholesky(sym, X)

    L = result["L"].toarray()
    d = result["d"]
    perm = sym["perm"]

    reconstructed = L @ np.diag(d) @ L.T
    X_dense = X.toarray()
    X_permuted = X_dense[np.ix_(perm, perm)]
    # X is stored with both triangles; symmetrize before comparing since
    # permuteP only ever reads whichever triangle L's own tril pattern
    # calls for.
    X_permuted = np.tril(X_permuted) + np.tril(X_permuted, -1).T

    np.testing.assert_allclose(reconstructed, X_permuted, rtol=1e-10, atol=1e-10)
