"""Phase 3-c: verify optstep.py against the real Octave build on a
pure-LP problem (K.f=0, K.q=[], K.s=[] -- the only scope this port
implements; see optstep.py's module docstring for why that's not a
limitation in practice).

Oracle data (tests/fixtures/sdinit/optstep.mat) is generated by
tools/generate_optstep_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.optstep import optstep  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


def test_optstep_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "optstep.mat")
    K = _load_K(data["K2"][0, 0])
    At2 = sp.csc_matrix(data["At2"])
    b2 = _densify(data["b2"])
    c2 = _densify(data["c2"])
    y0 = float(data["y0"].item())
    y = data["y"].ravel()
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    v = data["v"].ravel()
    dxmdz = data["dxmdz"].ravel()
    Lmat = data["L"][0, 0]
    L = {
        "L": sp.csc_matrix(Lmat["L"]),
        "d": Lmat["d"].ravel(),
        "skip": (np.nonzero(_densify(Lmat["skip"]))[0]).astype(np.int64),
        "perm": Lmat["perm"].ravel().astype(np.int64) - 1,
        "xsuper": Lmat["xsuper"].ravel().astype(np.int64) - 1,
        "tmpsiz": int(Lmat["tmpsiz"].item()),
    }
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "q": densemat["q"].ravel(), "l": int(densemat["l"].item())}
    Rmat = data["R"][0, 0]
    R = {fld: (Rmat[fld].ravel() if Rmat[fld].size > 1 else float(Rmat[fld].item())) for fld in Rmat.dtype.names}
    parsmat = data["pars"][0, 0]
    cgmat = parsmat["cg"][0, 0]
    cg = {fld: float(cgmat[fld].item()) for fld in cgmat.dtype.names}
    cholmat = parsmat["chol"][0, 0]
    chol = {fld: float(cholmat[fld].item()) for fld in cholmat.dtype.names}
    pars = {"cg": cg, "chol": chol, "eps": float(parsmat["eps"].item())}
    feasratio = float(data["feasratio"].item())

    x, y_out = optstep(At2, b2, c2, y0, y, d, v, dxmdz, K, L, None, dense, feasratio, R, pars)

    xsol = data["xsol"]
    if xsol.size == 0:
        assert x is None
    else:
        np.testing.assert_allclose(x, xsol.ravel(), rtol=1e-6, atol=1e-8)
        np.testing.assert_allclose(y_out, data["ysol"].ravel(), rtol=1e-6, atol=1e-8)
