"""Verify getdense.getdense against the real Octave getdense.m.

Oracle data (tests/fixtures/getdense/*.mat) is generated by
tools/generate_getdense_oracle.m and committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402
from sedumipy.getdense import getdense  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "getdense"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="getdense fixtures not generated"
)


def _run_case(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    At = sp.csc_matrix(data["A"])
    mainblks = data["mainblks"].ravel().astype(np.int64)
    K = {
        "l": int(data["Kl"].item()),
        "q": data["Kq"].ravel().astype(np.int64),
        "s": data["Ks"].ravel().astype(np.int64),
        "mainblks": mainblks,
        "qblkstart": data["qblkstart"].ravel().astype(np.int64),
        "sblkstart": data["sblkstart"].ravel().astype(np.int64),
        "lq": int(data["lq"].item()),
    }
    pars = {"denq": float(data["denq"].item()), "denf": float(data["denf"].item())}
    Ablkjc = _native.partitA(At, mainblks)

    dense, Adotdden = getdense(At, Ablkjc, K, pars)

    expected_l = int(data["dense_l"].item())
    expected_cols = data["dense_cols"].ravel().astype(np.int64)
    expected_q = data["dense_q"].ravel().astype(np.int64)
    expected_Adotdden = sp.csc_matrix(data["Adotdden"])

    assert dense["l"] == expected_l
    np.testing.assert_array_equal(dense["cols"], expected_cols)
    np.testing.assert_array_equal(dense["q"], expected_q)
    assert Adotdden.shape == expected_Adotdden.shape
    np.testing.assert_allclose(Adotdden.toarray(), expected_Adotdden.toarray())


def test_getdense_lp_dense_column():
    _run_case("case1")


def test_getdense_dense_lorentz_block():
    _run_case("case2")


def test_getdense_mixed_lp_lorentz_psd():
    _run_case("case3")


def test_getdense_nothing_dense():
    _run_case("case4")


def test_getdense_safety_valve_reset():
    _run_case("case5")
