"""Phase 3-c: verify neighborhood.iswnbr against the real Octave/MEX
build (iswnbr.c -- see neighborhood.py's module docstring for why this
is a from-scratch port rather than a ctypes binding: iswnbr.c's Q-set
sort has the exact same qsort-comparator undefined-behavior pattern
already confirmed to cause real divergence in sortnnz.c earlier in this
port).

Oracle data (tests/fixtures/iswnbr/*.mat) is generated by
tools/generate_iswnbr_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.neighborhood import iswnbr  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "iswnbr"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="iswnbr fixtures not generated"
)


@pytest.mark.parametrize("case", ["case1", "case2", "case3", "case4"])
def test_iswnbr_matches_octave(case):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{case}.mat")
    n = case[-1]
    w = data[f"w{n}"].ravel()
    theta = float(data[f"theta{n}"].item())

    delta, h, alpha = iswnbr(w, theta)

    assert delta == pytest.approx(float(data[f"delta{n}"].item()), rel=1e-8)
    assert h == pytest.approx(float(data[f"h{n}"].item()), rel=1e-8)
    assert alpha == pytest.approx(float(data[f"alpha{n}"].item()), rel=1e-8)
