"""Phase 3-c: verify deninfac.py's dense-column branch (Stage 5 of the
dense-columns optimization plan) against the real Octave build.

Oracle data (tests/fixtures/sdinit/deninfac_case{1,2}.mat) is generated by
tools/generate_deninfac_oracle.m and committed, so this test does not
require Octave to be installed to run.

Case 1 uses the default (large) pars.chol.maxuden -- dpr1fact.c's
pivoting branch (dopiv=1) is not exercised. Case 2 uses a deliberately
tiny maxuden plus artificially amplified dense-column data to force
dpr1fact's pivoting branch, and a hand-injected L.skip entry (with a
huge canceltol/abstol) to force deninfac.m's tail `Ld(skip(...))=1`
assignment branch -- see the generator script's own module docstring for
why hand-injecting L.skip this way is still a faithful test (that tail
logic is pure elementwise post-processing, independent of how L.skip was
produced).
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.deninfac import deninfac  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
CASES = ["deninfac_case1", "deninfac_case2"]
pytestmark = pytest.mark.skipif(
    not all((FIXTURE_DIR / f"{c}.mat").exists() for c in CASES),
    reason="deninfac fixtures not generated",
)


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


@pytest.mark.parametrize("case", CASES)
def test_deninfac_dense_branch_matches_octave(case):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{case}.mat")

    L = {
        "L": sp.csc_matrix(data["L_L"]),
        "d": data["L_d"].ravel(),
        "skip": np.nonzero(_densify(data["L_skip"]))[0].astype(np.int64),
        "perm": data["L_perm"].ravel().astype(np.int64) - 1,
        "xsuper": data["L_xsuper"].ravel().astype(np.int64) - 1,
    }
    densemat = data["dense"][0, 0]
    dense = {
        "l": int(densemat["l"].item()),
        "q": densemat["q"].ravel().astype(np.int64),
        "cols": densemat["cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix(densemat["A"]),
    }
    DAtmat = data["DAt"][0, 0]
    DAt = {"denq": sp.csc_matrix(DAtmat["denq"])}
    dmat = data["d"][0, 0]
    d = {"l": dmat["l"].ravel(), "det": dmat["det"].ravel()}
    symLden = {
        "LAD": sp.csc_matrix(data["symLden_LAD"]),
        "perm": data["symLden_perm"].ravel().astype(np.int64),
        "dz": sp.csc_matrix(data["symLden_dz"]),
        "first": data["symLden_first"].ravel().astype(np.int64),
    }
    absd = data["absd"].ravel()
    qblkstart = data["qblkstart"].ravel().astype(np.int64)
    pars_chol = data["pars_chol"][0, 0]
    pars = {
        "canceltol": float(pars_chol["canceltol"].item()),
        "abstol": float(pars_chol["abstol"].item()),
        "maxuden": float(pars_chol["maxuden"].item()),
    }

    Lden, Ld = deninfac(symLden, L, dense, DAt, d, absd, qblkstart, pars)

    np.testing.assert_array_equal(Lden["betajc"], data["Lden_betajc"].ravel())
    np.testing.assert_allclose(Lden["beta"], data["Lden_beta"].ravel(), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(Lden["p"], data["Lden_p"].ravel(), rtol=1e-8, atol=1e-10)
    np.testing.assert_array_equal(Lden["dopiv"], data["Lden_dopiv"].ravel())
    np.testing.assert_array_equal(Lden["pivperm"], data["Lden_pivperm"].ravel())
    np.testing.assert_allclose(Ld, data["Ld"].ravel(), rtol=1e-6, atol=1e-6)


def test_deninfac_no_dense_columns_branch():
    """dense.cols empty: Lden/Ld should be the trivial pass-through
    (the branch that predates Stage 5 and is unchanged by it)."""
    m = 4
    L = {
        "d": np.array([1.0, 2.0, 3.0, 4.0]),
        "skip": np.array([], dtype=np.int64),
        "perm": np.arange(m, dtype=np.int64),
    }
    dense = {"cols": np.zeros(0, dtype=np.int64)}

    Lden, Ld = deninfac(None, L, dense, {}, {}, np.ones(m), None, {"canceltol": 1e-12, "abstol": 1e-20})

    assert Lden["betajc"].tolist() == [0]
    np.testing.assert_array_equal(Lden["rowperm"], np.arange(1, m + 1))
    np.testing.assert_allclose(Ld, L["d"])
