"""Phase 3-c: verify pretransfo.py against the real Octave build across a
battery of cone-transformation scenarios (LP, free-variable split vs.
Lorentz-embedding, Lorentz cones, rotated Lorentz cones, real PSD (with
and without a diagonal block), complex Hermitian PSD (single block, and
all-complex), K.ycomplex, K.xcomplex, and a "kitchen sink" combining
several kinds at once).

Oracle data (tests/fixtures/pretransfo/*.mat) is generated by
tools/generate_pretransfo_oracle.m and committed, so this
test does not require Octave to be installed to run.

NOTE: "complex_sdp_mixed" (K.s=[2;3], K.scomplex=2 -- only the *second*
of two SDP blocks meant to be complex) is deliberately NOT one of the
oracle fixtures used here: it triggers a genuine bug in the real,
unmodified pretransfo.m (see pretransfo.py's module docstring) where
`scplx(K.scomplex&~sdiag)=true` silently marks *both* blocks complex
instead of just the one named, because a length-1 K.scomplex broadcasts
against the length-2 ~sdiag mask in MATLAB's `&`. Octave's own output
for that case reflects the bug, not the intended per-block selection, so
it cannot serve as ground truth for a corrected port. See
test_scomplex_partial_selection_not_octave_bug_compatible below for a
property-based (Octave-independent) check of the intended behavior
instead.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.pretransfo import pretransfo  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "pretransfo"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="pretransfo fixtures not generated"
)

CASES = [
    "lp_only",
    "free_split",
    "free_lorentz",
    "lorentz",
    "rotated_lorentz",
    "mixed_l_q_r",
    "real_sdp",
    "real_sdp_diag",
    "complex_sdp_single",
    "complex_sdp_all",
    "ycomplex",
    "xcomplex_mixed",
    "kitchen_sink_split",
    "kitchen_sink_lorentz",
]


def _load(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    At = data["At"]
    b = data["b"].ravel()
    c = data["c"].ravel()

    Kmat = data["K"][0, 0]
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in ("q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex"):
            K[fld] = val.item()
        else:
            K[fld] = val.ravel()

    parsmat = data["pars"][0, 0]
    pars = {fld: parsmat[fld].item() for fld in parsmat.dtype.names}
    return data, At, b, c, K, pars


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x)


@pytest.mark.parametrize("name", CASES)
def test_pretransfo_matches_octave(name):
    data, At, b, c, K, pars = _load(name)
    At2, b2, c2, K2, prep, origcoeff = pretransfo(At, b, c, K, pars)

    K2mat = data["K2"][0, 0]
    for fld in ("N", "l", "rsdpN", "m", "lq"):
        assert int(K2[fld]) == int(K2mat[fld].item()), fld
    for fld in ("q", "s"):
        np.testing.assert_array_equal(
            np.asarray(K2[fld]).ravel().astype(np.int64),
            K2mat[fld].ravel().astype(np.int64),
            err_msg=fld,
        )
    np.testing.assert_array_equal(
        np.asarray(K2["mainblks"]).ravel(), K2mat["mainblks"].ravel()
    )
    np.testing.assert_array_equal(
        np.asarray(K2["qblkstart"]).ravel(), K2mat["qblkstart"].ravel()
    )
    np.testing.assert_array_equal(
        np.asarray(K2["sblkstart"]).ravel(), K2mat["sblkstart"].ravel()
    )

    np.testing.assert_allclose(_densify(At2), _densify(data["At2"]), atol=1e-9)
    np.testing.assert_allclose(_densify(c2).ravel(), _densify(data["c2"]).ravel(), atol=1e-9)
    np.testing.assert_allclose(_densify(b2).ravel(), _densify(data["b2"]).ravel(), atol=1e-9)


def test_scomplex_partial_selection_not_octave_bug_compatible():
    """Property-based check (no Octave oracle -- see module docstring):
    marking only the SECOND of two SDP blocks complex must actually keep
    the first one real, unlike real pretransfo.m's own buggy behavior."""
    rng = np.random.default_rng(0)
    K = {"f": 0, "l": 0, "q": np.zeros(0), "r": np.zeros(0), "s": np.array([2, 3])}
    K["scomplex"] = np.array([2])
    n = int((K["s"] ** 2).sum())
    At = rng.random((n, 3)) - 0.5
    b = rng.random(3) - 0.5
    c = rng.random(n) - 0.5
    pars = {"free": 0, "sdp": 1, "errors": 0}

    _, _, _, K2, _, _ = pretransfo(At, b, c, K, pars)

    assert list(K2["s"]) == [2, 3]  # real block first, complex block second (already in that order)
    assert K2["rsdpN"] == 1  # exactly ONE real block -- not 0, which is what the Octave bug produces
    expected_N = 1 + 2 * 2 + 2 * (3 * 3)  # self-dual L + real 2x2 + complex 3x3 (doubled)
    assert K2["N"] == expected_N
