"""Phase 3-c: verify getdatm.py (DAt.q computation only -- no dense-
column correction) against the real Octave build.

Oracle data (tests/fixtures/sdinit/getdatm.mat) is generated by
tools/generate_getdatm_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.getdatm import getDAtm  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_getdatm_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "getdatm.mat")
    At2 = sp.csc_matrix(data["At2"])
    K2 = _load_K(data["K2"][0, 0])
    dmat = data["d"][0, 0]
    d = {fld: dmat[fld].ravel() for fld in dmat.dtype.names}
    densemat = data["dense"][0, 0]
    dense = {"q": densemat["q"].ravel(), "cols": densemat["cols"].ravel()}

    DAt = getDAtm(At2, dense, d, K2)

    DAt_exp = data["DAt"][0, 0]
    q_exp = DAt_exp["q"]
    q_exp = np.asarray(q_exp.todense() if sp.issparse(q_exp) else q_exp)
    np.testing.assert_allclose(DAt["q"], q_exp, rtol=1e-9, atol=1e-11)


def test_getdatm_raises_on_dense_q():
    K = {"q": np.array([3, 4])}
    dense = {"q": np.array([1]), "cols": np.array([1])}
    with pytest.raises(NotImplementedError):
        getDAtm(sp.csc_matrix((10, 3)), dense, {}, K)
