"""Verify _native.symbfwblk against the real Octave/MEX symbfwblk.

Oracle data (tests/fixtures/symbfwblk/*.mat) is generated by
tools/generate_symbfwblk_oracle.m and committed, so this test does not
require Octave to be installed to run.

symbfwblk computes a symbolic (pattern-only) forward solve: every entry
it flags nonzero is set to 1.0 by the C kernel regardless of what a
numeric solve would actually produce, so this test compares nonzero
*patterns*, not values.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "symbfwblk"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="symbfwblk fixtures not generated"
)


def _run_case(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    L = {
        "perm": data["L_perm"].ravel().astype(np.int64),
        "L": sp.csc_matrix(data["L_L"]),
        "xsuper": data["L_xsuper"].ravel().astype(np.int64),
    }
    B = sp.csc_matrix(data["B"])
    expected_pattern = np.asarray(data["Xpat"].todense()) != 0

    got = _native.symbfwblk(L, B)

    assert got.shape == expected_pattern.shape
    np.testing.assert_array_equal(np.asarray(got.todense()) != 0, expected_pattern)


def test_symbfwblk_chain_pattern():
    _run_case("case1")


def test_symbfwblk_disconnected_blocks():
    _run_case("case2")


def test_symbfwblk_larger_random_pattern():
    _run_case("case3")
