"""Phase 2 cluster 4 (partial): verify partitA, findblks, extractA (the
sparse row-range utilities behind SeDuMi's Schur-complement assembly)
against the real Octave/MEX build.

Scope note: getada1/getada2 (no separable C core -- their entire
computation lives directly in mexFunction, unlike every other kernel in
this port) and getada3/adendotd/adenscale (deeply tied to sedumi.m's
internal "dense columns" bookkeeping -- dense.{cols,l,q,A} and
d.{q1,q2} structs that only make sense in the context of the full
algorithm) are deliberately NOT covered here. They are deferred to
Phase 3, where porting sedumi.m/optstep.m itself will supply the real
context needed to either port their logic straight to NumPy (getada1/
getada2, following qblkmul's precedent) or bind them properly (getada3/
adendotd/adenscale) -- see the cluster 4 task for the scope discussion
this was raised with the user.

Oracle data (tests/fixtures/cluster4/*.mat) is generated by
tools/generate_cluster4_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cluster4"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cluster4 fixtures not generated"
)


def test_partitA_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "partitA.mat")
    got = _native.partitA(data["At"].tocsc(), data["blkstart3"].ravel())
    np.testing.assert_array_equal(got, data["Ablkjc"])


def test_findblks_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "findblks.mat")
    got = _native.findblks(
        data["At"].tocsc(), data["Ablkjc2"], 1, 2, data["blkstart2"].ravel()
    )
    np.testing.assert_array_equal(got.toarray(), data["Ablk"].toarray())


def test_extractA_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "extractA.mat")
    got = _native.extractA(data["At"].tocsc(), data["Ablkjc2"], 2, 3, [3, 7])
    np.testing.assert_allclose(got.toarray(), data["Apart"].toarray())


def test_extractA_matches_direct_dense_slice():
    """Independent of the oracle: extractA with a properly-computed
    Ajc table (from partitA) must reproduce a plain dense row slice."""
    import scipy.sparse

    rng = np.random.default_rng(5)
    At = scipy.sparse.random(8, 5, density=0.4, random_state=rng, format="csc")
    Ablkjc = _native.partitA(At, [1, 4, 9])
    got = _native.extractA(At, Ablkjc, 2, 3, [4, 9])
    np.testing.assert_allclose(got.toarray(), At.toarray()[3:8, :])
