"""Phase 3-c: verify amul.py and sdinit.py against the real Octave build.

sdinit's own oracle uses real (not complex) SDP blocks only: its
vfrm.s = qrK(d.u,K) call would be silently wrong for a complex block
until _native.qrK's existing binding (cluster 3, real-symmetric-blocks-
only by its own admission) gets a complex-block path -- see
generate_sdinit_oracle.m's comment.

Oracle data (tests/fixtures/sdinit/*.mat) is generated by
tools/generate_sdinit_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.amul import amul  # noqa: E402
from sedumipy.sdinit import sdinit  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)


def _densify(x):
    return np.asarray(x.todense() if sp.issparse(x) else x).ravel()


def test_amul_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "amul.mat")
    Amat = data["Amat"]
    At = sp.csc_matrix(Amat)
    xN = data["xN"].ravel()
    xm = data["xm"].ravel()
    dense2mat = data["dense2"][0, 0]
    dense2 = {"cols": dense2mat["cols"].ravel(), "A": dense2mat["A"]}
    dense_empty = {"cols": np.zeros(0, dtype=np.int64), "A": sp.csc_matrix((Amat.shape[1], 0))}

    np.testing.assert_allclose(amul(At, dense2, xN, transp=False), _densify(data["y_transp0"]))
    np.testing.assert_allclose(amul(At, dense2, xm, transp=True), _densify(data["y_transp1"]))
    np.testing.assert_allclose(
        amul(At, dense_empty, xN, transp=False), _densify(data["y_transp0_nodense"])
    )
    np.testing.assert_allclose(
        amul(At, dense_empty, xm, transp=True), _densify(data["y_transp1_nodense"])
    )


_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_sdinit_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "sdinit_case1.mat")
    At2 = sp.csc_matrix(data["At2"])
    b2 = _densify(data["b2"])
    c2 = _densify(data["c2"])
    K2 = _load_K(data["K2"][0, 0])
    parsmat = data["pars"][0, 0]
    pars = {}
    for fld in parsmat.dtype.names:
        val = parsmat[fld]
        pars[fld] = val.ravel() if fld == "w" else (val.item() if val.size == 1 else val)
    densemat = data["dense"][0, 0]
    dense = {"cols": densemat["cols"].ravel(), "A": densemat["A"]}

    d, v, vfrm, y, y0, R = sdinit(At2, b2, c2, dense, K2, pars)

    d_exp = data["d"][0, 0]
    for fld in ("l", "det", "q1", "q2", "auxdet", "auxtr", "u"):
        np.testing.assert_allclose(d[fld], d_exp[fld].ravel(), rtol=1e-10, atol=1e-12, err_msg=fld)

    vfrm_exp = data["vfrm"][0, 0]
    np.testing.assert_allclose(vfrm["lab"], vfrm_exp["lab"].ravel(), rtol=1e-10)
    np.testing.assert_allclose(vfrm["q"], vfrm_exp["q"].ravel(), rtol=1e-10)
    np.testing.assert_allclose(vfrm["s"], vfrm_exp["s"].ravel(), rtol=1e-8, atol=1e-10)

    np.testing.assert_allclose(y, data["y"].ravel())
    assert y0 == pytest.approx(float(data["y0"].item()), rel=1e-10)

    R_exp = data["R"][0, 0]
    for fld in ("maxb", "maxc", "b0", "sd", "maxRb", "maxRc", "norm"):
        assert R[fld] == pytest.approx(float(R_exp[fld].item()), rel=1e-9), fld
    np.testing.assert_allclose(R["b"], R_exp["b"].ravel(), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(R["c"], R_exp["c"].ravel(), rtol=1e-8, atol=1e-10)
    np.testing.assert_allclose(R["w"], R_exp["w"].ravel(), rtol=1e-9)
