"""Phase 2 cluster 1: verify ddot, qblkmul, vecsym, quadadd against the
real Octave/MEX build. (blkmul is bound too, but is dead code -- not
referenced by install_sedumi.m or any .m file, no real MEX build exists
to check it against; see generate_cluster1_oracle.m.)

Oracle data (tests/fixtures/cluster1/*.mat) is generated by
tools/generate_cluster1_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cluster1"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cluster1 fixtures not generated"
)


def test_ddot_dense_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "ddot_dense.mat")
    d = data["d"].ravel()
    X = data["X"]
    blkstart = data["blkstart"].ravel().astype(np.int64)
    expected = data["ddotX"]

    got = _native.ddot(d, X, blkstart)
    np.testing.assert_allclose(got, expected, rtol=1e-12)


def test_ddot_dense_offset_matches_octave_mex():
    """Regression test for a real gap found while porting qjmul.m/Phase
    3-b: ddot.c's own mexFunction (not just its ddotxj() core, which
    ddot() wraps directly) applies a row offset when X is given as a
    full, absolute-indexed array (blkstart[0] > 1) rather than pre-sliced
    to the block span -- ddot() didn't replicate that offset before this
    fixture was added, so it silently read from the wrong rows of X
    whenever blkstart didn't start at 1 (not exercised by
    test_ddot_dense_matches_octave_mex's blkstart=[1;3;7])."""
    data = scipy.io.loadmat(FIXTURE_DIR / "ddot_offset.mat")
    got = _native.ddot(data["d2"].ravel(), data["X2"], data["blkstart2"].ravel())
    np.testing.assert_allclose(got, data["ddotX2"], rtol=1e-12)


def test_qblkmul_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "qblkmul.mat")
    got = _native.qblkmul(
        data["mu"].ravel(), data["dq"].ravel(), data["blkstartq"].ravel()
    )
    np.testing.assert_allclose(got, data["yq"].ravel(), rtol=1e-12)


def test_vecsym_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "vecsym.mat")
    K = {"l": int(data["Kl"].item()), "s": data["Ks"].ravel().tolist()}
    got = _native.vecsym(data["xv"].ravel(), K)
    np.testing.assert_allclose(got, data["yv"].ravel(), rtol=1e-12)


def test_quadadd_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "quadadd.mat")
    zhi, zlo = _native.quadadd(
        data["xhi"].ravel(), data["xlo"].ravel(), data["yqa"].ravel()
    )
    np.testing.assert_allclose(zhi, data["zhi"].ravel(), rtol=1e-12)
    np.testing.assert_allclose(zlo, data["zlo"].ravel(), rtol=1e-12)


def test_vecsym_is_idempotent_and_symmetrizes():
    """Independent of the oracle: vecsym(vecsym(x)) == vecsym(x), and the
    PSD blocks of the output are exactly symmetric."""
    K = {"l": 1, "s": [3]}
    x = np.random.default_rng(0).standard_normal(1 + 9)
    once = _native.vecsym(x, K)
    twice = _native.vecsym(once, K)
    np.testing.assert_allclose(once, twice)

    block = once[1:].reshape(3, 3, order="F")
    np.testing.assert_allclose(block, block.T)
