"""Phase 3-c: verify updtransfo.py against the real Octave build, using
a genuine `w` struct built the same way trydif.m/widelen.m do (tdet/
psdfactor/psdscale/psdeig) and the same mixed L+Lorentz+real-SDP problem
as the recent sdinit/getDAtm/PopK/pcg/sddir fixtures.

Real (not complex) PSD blocks only, matching the existing qrK/
urotorder/givensrot/sqrtinv native bindings' own scope (see
updtransfo.py's module docstring).

Oracle data (tests/fixtures/sdinit/updtransfo.mat) is generated by
tools/generate_updtransfo_oracle.m and committed, so this
test does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.updtransfo import updtransfo  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "sdinit"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="sdinit fixtures not generated"
)

_INT_SCALAR_FIELDS = {"f", "l", "rsdpN", "N", "m", "lq", "rLen", "hLen", "qMaxn", "rMaxn", "hMaxn"}


def _load_K(Kmat):
    K = {}
    for fld in Kmat.dtype.names:
        val = Kmat[fld]
        if val.size == 1 and fld not in (
            "q", "r", "s", "z", "ycomplex", "xcomplex", "scomplex", "fcplx", "qcplx", "rcplx",
            "mainblks", "qblkstart", "sblkstart", "blkstart",
        ):
            K[fld] = int(val.item()) if fld in _INT_SCALAR_FIELDS else val.item()
        else:
            K[fld] = val.ravel()
    return K


def test_updtransfo_matches_octave():
    data = scipy.io.loadmat(FIXTURE_DIR / "updtransfo.mat")
    K = _load_K(data["K2"][0, 0])
    dINmat = data["dIN"][0, 0]
    dIN = {fld: dINmat[fld].ravel() for fld in dINmat.dtype.names}
    dIN["perm"] = np.zeros(0)
    wmat = data["w"][0, 0]
    w = {fld: wmat[fld].ravel() for fld in wmat.dtype.names}
    x = data["x"].ravel()
    z = data["z"].ravel()

    d, vfrm = updtransfo(x, z, w, dIN, K)

    d_exp = data["d"][0, 0]
    for fld in ("l", "det", "q1", "q2", "auxdet", "auxtr", "u"):
        np.testing.assert_allclose(d[fld], d_exp[fld].ravel(), rtol=1e-6, atol=1e-8, err_msg=fld)
    # d.perm is a permutation choice, not unique for degenerate spectra --
    # checked via its defining consistency property below instead of a
    # direct comparison to Octave's own arbitrary tie-breaking.
    np.testing.assert_array_equal(sorted(d["perm"]), sorted(d_exp["perm"].ravel()))

    vfrm_exp = data["vfrm"][0, 0]
    np.testing.assert_allclose(vfrm["lab"], vfrm_exp["lab"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(vfrm["q"], vfrm_exp["q"].ravel(), rtol=1e-6, atol=1e-8)
    np.testing.assert_allclose(vfrm["s"], vfrm_exp["s"].ravel(), rtol=1e-6, atol=1e-8)
