"""Verify symbcholden.symbcholden against the real Octave symbcholden.m.

Oracle data (tests/fixtures/symbcholden/*.mat) is generated by
tools/generate_symbcholden_oracle.m and committed, so this test does
not require Octave to be installed to run. The oracle's `L` struct is
produced by this port's own symbchol() (not read from the fixture),
mirroring how symbcholden.py is actually invoked from sedumi.py.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io
import scipy.sparse as sp

sedumipy = pytest.importorskip("sedumipy")
from sedumipy.symbchol import symbchol  # noqa: E402
from sedumipy.symbcholden import symbcholden  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "symbcholden"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="symbcholden fixtures not generated"
)


def _run_case(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    X = sp.csc_matrix(data["X"])
    L = symbchol(X)

    dense = {
        "l": int(data["dense_l"].item()),
        "q": data["dense_q"].ravel().astype(np.int64),
        "cols": data["dense_cols"].ravel().astype(np.int64),
        "A": sp.csc_matrix(data["dense_A"]),
    }
    DAt = {"denq": sp.csc_matrix(data["DAt_denq"])}

    Lden = symbcholden(L, dense, DAt)

    expected_LAD_pattern = np.asarray(data["Lden_LAD"].todense()) != 0
    np.testing.assert_array_equal(
        np.asarray(Lden["LAD"].todense()) != 0, expected_LAD_pattern
    )
    np.testing.assert_array_equal(Lden["perm"], data["Lden_perm"].ravel().astype(np.int64))
    np.testing.assert_array_equal(Lden["first"], data["Lden_first"].ravel().astype(np.int64))
    np.testing.assert_array_equal(
        np.asarray(Lden["dz"].todense()), np.asarray(data["Lden_dz"].todense())
    )


def test_symbcholden_lp_and_one_lorentz_block():
    _run_case("case1")


def test_symbcholden_two_lorentz_blocks_no_lp():
    _run_case("case2")


def test_symbcholden_lp_only_no_lorentz():
    _run_case("case3")
