"""Phase 3-b: verify cone.py (eigK, maxeigK, mineigK, eyeK, vec, mat --
pure NumPy ports of the corresponding .m files, which are themselves
plain MATLAB, not MEX functions) against the real Octave build.

Covers SeDuMi's INTERNAL cone-K representation only (K.rsdpN present),
mixing LP + two Lorentz blocks + one real PSD block + one complex
Hermitian PSD block -- the only representation sedumi.m's own iteration
loop actually uses (eyeK is called exactly once in the whole codebase,
from sdinit.m, always with this representation). The "external" cone
format branch in each of eigK.m/maxeigK.m/mineigK.m/eyeK.m is ported in
cone.py too, but not verified here; eyeK.m's external-format branch was
found to have a pre-existing bug when K.q is set without K.f (crashes
with "structure has no member 'f'" in real Octave) -- irrelevant to
sedumi.m's own usage, so not chased further.

Oracle data (tests/fixtures/cone/eigK.mat) is generated by
tools/generate_cone_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import cone  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cone"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cone fixtures not generated"
)


def _load():
    data = scipy.io.loadmat(FIXTURE_DIR / "eigK.mat")
    K = {
        "l": int(data["Kl"].item()),
        "q": data["Kq"].ravel().tolist(),
        "s": data["Ks"].ravel().tolist(),
        "rsdpN": int(data["KrsdpN"].item()),
        "N": int(data["KN"].item()),
    }
    return data, K


def test_eigK_matches_octave():
    data, K = _load()
    lab = cone.eigK(data["x"].ravel(), K)
    np.testing.assert_allclose(np.sort(lab), np.sort(data["lab"].ravel()), rtol=1e-10)
    # eigK doesn't sort within a PSD block's own eigenvalues against
    # other blocks, but numpy.linalg.eigvalsh and MATLAB/LAPACK's
    # symmetric eigensolver should agree on the *order within each
    # block* (both ascending) -- check the unsorted vector too.
    np.testing.assert_allclose(lab, data["lab"].ravel(), rtol=1e-10)


def test_maxeigK_matches_octave():
    data, K = _load()
    got = cone.maxeigK(data["x"].ravel(), K)
    np.testing.assert_allclose(got, float(data["labmax"].item()), rtol=1e-10)


def test_mineigK_matches_octave():
    data, K = _load()
    got = cone.mineigK(data["x"].ravel(), K)
    np.testing.assert_allclose(got, float(data["labmin"].item()), rtol=1e-10)


def test_eyeK_matches_octave():
    data, K = _load()
    got = cone.eyeK(K)
    np.testing.assert_allclose(got, data["idK"].ravel(), rtol=1e-10)


def test_maxeigK_and_mineigK_are_extremes_of_eigK():
    """Independent of the oracle: maxeigK/mineigK must equal max/min of
    the full spectral value vector eigK returns, by definition -- checked
    on a Lorentz-free cone (LP + PSD only), since mineigK.m (unlike
    eigK.m/maxeigK.m) has no is_int branch for Lorentz blocks: it always
    assumes the "external", x0-immediately-followed-by-vector layout,
    even when called with K.rsdpN present, so it disagrees with eigK's
    own (is_int-aware) reading of an x vector built in the "internal",
    x0-values-stacked-first layout the main fixture uses. That
    disagreement is a property of the real mineigK.m (confirmed against
    Octave), not a bug in this port, so it isn't asserted away here."""
    data, K = _load()
    K_no_q = dict(K)
    K_no_q["q"] = []
    x = data["x"].ravel()
    x_no_q = np.concatenate([x[: K["l"]], x[K["l"] + int(sum(K["q"])) :]])

    lab = cone.eigK(x_no_q, K_no_q)
    assert cone.maxeigK(x_no_q, K_no_q) == pytest.approx(np.max(lab))
    assert cone.mineigK(x_no_q, K_no_q) == pytest.approx(np.min(lab))


def test_eyeK_has_eigK_all_ones():
    """Independent of the oracle: the cone's identity element must have
    every spectral value equal to 1, by definition of eyeK."""
    _, K = _load()
    idK = cone.eyeK(K)
    lab = cone.eigK(idK, K)
    np.testing.assert_allclose(lab, np.ones_like(lab), atol=1e-10)


def test_vec_mat_roundtrip():
    rng = np.random.default_rng(0)
    X = rng.standard_normal((4, 4))
    np.testing.assert_array_equal(cone.mat(cone.vec(X)), X)
