"""Phase 3 (symbolic Cholesky ordering, step 1): verify the ordmmd()
ctypes binding produces EXACTLY the same permutation as the real Octave/
MEX ordmmdmex() -- not just "a valid minimum degree ordering" in the
abstract sense (many exist for a given graph), but bit-for-bit the same
one, since it is the exact same ordmmd.c/genmmd.c source running through
a different (mex.h-free) calling convention.

The oracle files (tests/fixtures/ordmmd/*_oracle.mat) are generated by
running the actual Octave/MEX build via
tools/generate_ordmmd_oracle.m -- see that file and
tests/fixtures/generate_ordmmd_fixtures.py for how the inputs and the
oracle outputs were produced. Both are committed, so this test does not
require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumipy = pytest.importorskip("sedumipy")
from sedumipy import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "ordmmd"


def _fixture_names():
    if not FIXTURE_DIR.exists():
        return []
    return sorted(
        p.stem for p in FIXTURE_DIR.glob("*.mat") if not p.stem.endswith("_oracle")
    )


@pytest.mark.skipif(not _fixture_names(), reason="ordmmd fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_ordmmd_matches_octave_mex_exactly(name):
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    oracle = scipy.io.loadmat(FIXTURE_DIR / f"{name}_oracle.mat")

    A = data["A"].tocsc()
    expected_perm_1indexed = np.asarray(oracle["perm"]).squeeze().astype(np.intp)

    perm_0indexed = _native.ordmmd(A)

    np.testing.assert_array_equal(perm_0indexed + 1, expected_perm_1indexed)


@pytest.mark.skipif(not _fixture_names(), reason="ordmmd fixtures not generated")
@pytest.mark.parametrize("name", _fixture_names())
def test_ordmmd_returns_a_valid_permutation(name):
    """Independent of the Octave oracle: perm must be a permutation of
    0..n-1, regardless of which specific ordering the heuristic picks."""
    data = scipy.io.loadmat(FIXTURE_DIR / f"{name}.mat")
    A = data["A"].tocsc()
    n = A.shape[0]

    perm = _native.ordmmd(A)

    assert perm.shape == (n,)
    assert set(perm.tolist()) == set(range(n))
